### ISSUE TITLE
MAX_BATCH_READ_SIZE?

### ISSUE THREAD

**Issue by craigsketchley** [dynamoosejs/dynamoose#110]
I'm getting some errors when I exceed the maximum item count from `batchGet` requests. I see you're chunking `batchPut` requests but not `batchGet`. I noticed you have `MAX_BATCH_READ_SIZE` [commented out](https://github.com/automategreen/dynamoose/blob/master/lib/Model.js#L10).

Anything I can help with?

**Comment by brandongoode** [comment]
Ya, looks like an oversight.  If you would like to work on "chunking" the request, a PR would be great! Could you add a couple test cases for the "chunking" behavior too?

**Comment by fishcharlie** [comment]
@craigsketchley Want to try to get a PR submitted for this? 😃

**Comment by fishcharlie** [comment]
Not quite sure what needs to be done to get this working. @brandongoode any input?
