### ISSUE TITLE
ExclusiveStartKey not converted into DynamoDB Format in Query and Scan

### ISSUE THREAD

**Issue by AlexanderFillbrunn** [dynamoosejs/dynamoose#114]
When using an exclusive start key in a scan or query, Dynamoose does not seem to convert this into a proper DynamoDB-Object. The code below produces an error.
```
await Dog.create({
      ownerId : 1,
      name : 'Testdog',
      color : ['Pink'],
      age : 10,
      breed : 'Retriever'
  });

  await Dog.create({
      ownerId : 1,
      name : 'Testdog2',
      color : ['Red'],
      age : 11,
      breed : 'Pekinese'
  });

  await Dog.create({
      ownerId : 1,
      name : 'Testdog3',
      color : ['Yellow'],
      age : 15,
      breed : 'Labrador'
  });

  await Dog.query('ownerId').eq(1).startAt({ownerId: 1, name: 'Testdog2'}).exec();
```
This gives the following error:
```
* InvalidParameterType: Expected params.ExclusiveStartKey['ownerId'] to be a structure
* InvalidParameterType: Expected params.ExclusiveStartKey['name'] to be a structure
...
```
Changing the exclusive start key manually to correspond to the format required by DynamoDB fixes the problem:
```
await Dog.query('ownerId').eq(1).startAt({ownerId: {N : '1'}, name: {S: 'Testdog2'}}).exec();

> [ NewModel {
    ownerId: 1,
    name: 'Testdog3',
    breed: 'Labrador',
    color: [ 'yellow' ],
    age: 15 },
  lastKey: undefined ]
```
I think it would be consistent to not require the user to format the start key in this way, as other data is also converted automatically.

**Comment by brandongoode** [comment]
Ya, I agree. (Again sorry for the slow response)

The startAt was designed to work with the `lastKey` returned in the scan and query results.  Both really should be converted.  Something to look at cleaning up in a future release.
