### ISSUE TITLE
Project cleanups

### ISSUE THREAD

**Issue by vangorra** [dynamoosejs/dynamoose#129]
I browsing the code, I noticed a few things about the project structure and setup that could use some attention. I'd like to submit a PR with the fixes but would like to discuss the changed before making a bunch of changes.

- [x] Use explicit module versions in package.json - Currently it is using * as dependency versions. This make for totally unreliable builds as we don't know which versions of dependencies are being used today nor 3 months from now. Case in point, mocha 3.0.0 dropped support for html-cov. So the html coverage reporting will not work unless we explicily set an older version of that dependency.
- [ ] Enable npm shrinkwrap - This will ensure the versions of the packages used on the project are always set regardless of what was released later. Makes for very predictable builds. This will require that occasionally we update the dependencies manially via npm install module@version --save.[-dev]
- [ ] Use a dedicated build/dist directory - Keep all our temp files during build and test in one place. Will help keep .gitignore clean.
- [x] Code coverage to output standard coverage format - Use something like lcov. This directly flows into the next point.
- [x] Enable codecov.io integration with github - Using a .codecov.yml file in the root, the gated coverage requirements can be visually seen on each pull request. So a contributor will know immediately and quite clearly if their code passes and if it has enough coverage. Enabling access is something the project owner will have to enable. I can add the config files and other necessary stuff.
- [ ] Optimized documentation - Some improvements can be made to make things a bit more clear.
- [ ] Switch to gulp instead of grunt - Mostly, with the automated setup of a local dynamodb for testing, it would be good to have that process tear down too. Sadly with grunt that is not so simple. Gulp tends to allow for this sort of flexibility and has a lot more community support.
- [ ] Using Istanbul instead of blanket - blanket is inactive and they even recommend using Istanbul instead.

Thoughts?

**Comment by brandongoode** [comment]
I agree completely.   The code needs some TLC.  My one request is to use separate PR for each main update.  It makes reviewing and merging a lot easier.   

I switched some of my other repos to istanbul and coveralls.io.  However, I think codecov.io is a better option.

I've used both gulp and grunt, but am no expert with either.  So, if gulp works better with `dynamodb-local`, I'm cool with the change.

On the documentation updates, what were you thinking?  I've wanted to redo the doc for a long time.  I would like to move to using Github Pages in a docs folder using jekyll.  I could setup the basic structure and copy the current readme.  I may also get a nice domain like (dynamoosejs.com) just to make the project look a little more polished.

**Comment by troyswanson** [comment]
Throwing my 🎩 into the 💍...

I'm happy to help with the documentation upgrades. I'm a (legacy) member of the Jekyll org and I've been doing Jekyll sites for many years now.

**Comment by vangorra** [comment]
Great, will keep it all as separate PRs.

**CodeCov**
Just setup the account and give them access to this repo. I'll just need the token for the travis build step to upload the coverage files.
I'll also get Istanbul running.

**Documentation**
I was thinking about just being more explicit about return types and such. For example it's not clean if Model.get returns a model, plain object or dynamo result. It returns a model which of course is the preferred solution.
@troyswanon I will defer to you on your expertise here as I admittedly do not have the experience to setup documentation well. Would it be more feasible to create a separate dynamoose-documentation repository and populate it with all the .rst files? Then it would look pretty.

**Comment by troyswanson** [comment]
To start with on the documentation, I think we can move detailed usage docs into the GitHub Wiki. The README can be cleaned up to be more focused on quickly setting up dynamoose. Once a good structure for the documentation is set up in the Wiki, we can migrate that into a Jekyll site which will be automatically hosted by GitHub for free.

We can move the discussion around the documentation project over to #126.

**Comment by brandongoode** [comment]
@troyswanson  -- Thanks, I've got a few Jekyll site but only touch the config ever once in a while.  I seem to have to re-learn it every time.

I agree we'll keep the documenation site updates on #126.

**Comment by fishcharlie** [comment]
Although these are still good ideas. I'm closing this issue for now. It has been inactive for quite a while. If anyone wants to make PRs for this stuff, I'd be more than happy to review and help get it in.
