### ISSUE TITLE
Recording Update History

### ISSUE THREAD

**Issue by mogwai** [dynamoosejs/dynamoose#159]
## Summary
I want the version to show the changes that have happened to an entry, saving previous versions in a new row. Or, these oldVersions could be saved in the object itself if there is already a convention that uses the __v or _version field #16.

When compiling the model: 

```javascript
var Model = dynamoose.model('Models', Model, {versioning:true})
```

This would result in the schema having a __v field which specifies 

```javascript
{
    name: {
        type: String,
        hashKey: true,
    },
    __v: {
        type: Number,
        default: 1
    },
    createdAt: { // Will now be when this update occured
        type: Date,
    },
    updatedAt: { // When this was changed
        type: Date,
    }
}
```

## Requirements

- Queries to the database will automatically get the latest version of an item 
- Putting and Saving items will automatically increment the __version number and create a new item 

## Results
- Will allow developers to implement reverting back to previous versions

**Comment by troyswanson** [comment]
This is a cool idea! 👍 

IMO, storing the previous version within the same object makes the most sense, in case you are using a unique ID as the hash key.

Maybe you could specify which fields need to be versioned? This can be done in the schema instead of the model creation.

```json
{
  "id": "ABC",
  "name": "Version 3 -- The second update",
  "__v": {
    "number": 3,
    "history": [{
      "name": "Version 1 -- The original string",
      "createdAt": "<timestamp_1>"
    }, {
      "name": "Version 2 -- The first update",
      "createdAt": "<timestamp_2>"
    }]
  },
  "createdAt": "<timestamp_1>",
  "updatedAt": "<timestamp_3>"
}
```

Thoughts?

**Comment by lengk** [comment]
> Maybe you could specify which fields need to be versioned? This can be done in the schema instead of the model creation.

Yes but if you do that, will all the fields selected be saved in the history or just what changed? 
When querying the database this could increase bandwidth as a database gets older. Is there a way to query dynamo asking for a certain part of the object to not be included:

```javascript
User.get({
        username:"user"
    }, 
    {
        __v: false
    })
```


Agree with remove of updatedAt in the history field entries.

**Comment by troyswanson** [comment]
> When querying the database this could increase bandwidth as a database gets older.

This is a good point, and your method of dealing with that makes the most sense. I don't think what you're asking for is possible, however.

If I understand how throughput works in DynamoDB correctly, doing a `get` on a hash key field will transfer the entire document (indeed all documents that match the hash key) through the pipe. It's for this same reason that storing data in separate documents won't solve the problem either...

---

There might be a way to deal with this once #138 is implemented out of the box (kinda)... You could create a schema that looks something like this:

**UserVersion**
```json
{
  "userversion_id": "ABC",
  "userdata_id": "xyz",
  "version": {
    "number": 3,
    "history": ["qrs", "tuv"]
  },
  "createdAt": "<timestamp_1>",
  "updatedAt": "<timestamp_3>"
}
```

**UserData**
```json
{
  "userdata_id": "xyz",
  "username": "<current username>",
  "createdAt": "<timestamp_3>"
}
```
```json
{
  "userdata_id": "tuv",
  "username": "<previous revision username>",
  "createdAt": "<timestamp_2>"
}
```
```json
{
  "userdata_id": "qrs",
  "username": "<original username>",
  "createdAt": "<timestamp_1>"
}
```

Then you can use the `populate` method to populate the `UserVersion` object with the reference to the correct `UserData` document... I'm basically just thinking as I type right now. Thoughts?

**Comment by lengk** [comment]
Separating them like this seems to be the best way. I think that UserData should be User_History. Also I don't see why we can't call UserVersion just user. This means someone using it can easily see which table to look at.

Do you think that the User (UserVersion) table could include the most up to date version of the table. That way you would most of the time only need to query the one table? Also this would mean you wouldn't need to store the current version in database but I think leaving it is fine.  I think having the userversion_id in the User_History table would be good too.

**Comment by brandongoode** [comment]
Great ideas and conversation.

One idea that I've been toying with as a major part of v0.9 is adding support for plugins.  I want to be able to support use cases such as this without having to modify the core functionality of dynamoose.

**Comment by lengk** [comment]
@brandongoode This feature will not be necessary for everyone so probably best left for a plugin?

**Comment by fishcharlie** [comment]
I have started work on PR #325 to implement plugins into Dynamoose. I would **love** feedback during this process to ensure this feature is made possible. This feature is something I'm consistently thinking about to make sure this feature possible with Dynamoose Plugin Support.

Feel free to comment on that PR throughout the building process. I'm trying to build this feature out in the open so I can potential get feedback about the direction we are taking on it.

**Comment by fishcharlie** [comment]
I have also opened a PR (#338) that should help to build out this functionality as a plugin when Dynamoose version 0.9 is released.

**Comment by fishcharlie** [comment]
@mogwai Wanna give this a shot in the new Dynamoose Plugin Beta system, and let me know if it's possible or if I need to make any changes to the API to make this happen, along with any feedback you have?

**Comment by fishcharlie** [comment]
Closing this issue has it has been migrated to our new plugin ideas repo.

https://github.com/dynamoosejs/dynamoose-plugin-ideas/issues/1
