### ISSUE TITLE
Clone Databases from DynamoDB to DynamoDB Local

### ISSUE THREAD

**Issue by fishcharlie** [dynamoosejs/dynamoose#164]
Currently I have a few models/databases setup in Dynamoose. I have a system variable to detect if the system is production or development. If it is development it uses DynamoDB Local, otherwise it uses the production version of DynamoDB.

On my development machine it would be great to have an easy way to clone those DynamoDB production databases to my local DynamoDB databases.

Maybe this is a feature that would always be easiest to build up from scratch using the current Dynamoose features. Not sure how this feature would even be integrated. But something to look into maybe.

**Comment by brandongoode** [comment]
Great idea.  It may be best to create a separate utility for this.  You could run a scan and batchPut in a loop.  The challenge will be creating two dynamoose instances for each DB. This may require some changes to dynamoose.

**Comment by fishcharlie** [comment]
@mogwai I think it would be a one time thing. But maybe I could add an option for listening for changes. Originally my use case would be better fit for one time thing. But listening for changes is interesting too.

**Comment by fishcharlie** [comment]
Closing this since it has been migrated to our new plugin ideas repo.

https://github.com/dynamoosejs/dynamoose-plugin-ideas/issues/2
