### ISSUE TITLE
Update nested values

### ISSUE THREAD

**Issue by larrybek** [dynamoosejs/dynamoose#165]
I want to update nested value in my database.
Can anyone suggest best solution for it?

**Comment by brandongoode** [comment]
The only option using dynamoose today is to get the full attribute, modify the nested value, and then update the entire attribute.

DynamoDB does support setting a nested attribute, but this isn't supported yet: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.UpdateExpressions.html#Expressions.UpdateExpressions.SET.AddingNestedMapAttributes

**Comment by lrcry** [comment]
@brandongoode  @larrybek  I think it is a similar issue as the nested scan. Maybe we need to consider to update the whole library to use the document client to fully support nested features.

**Comment by brandongoode** [comment]
@lrcry I agree.  Let's look at updating it in the 0.9 release.

**Comment by androidand** [comment]
This would be nice. I'm struggling with updating nested values at the moment.

**Comment by xiaoyufan** [comment]
Any update on this?

**Comment by fishcharlie** [comment]
@xiaoyufan No updates on this. Feel free to work on it and submit a PR.

**Comment by olurocks** [comment]
so about 6 years down the line ... still no update on this??

**Comment by fishcharlie** [comment]
Locking this issue. Please see #1589.
