### ISSUE TITLE
Support for plugins

### ISSUE THREAD

**Issue by benjcooley** [dynamoosejs/dynamoose#18]
MongoDB mongoose supports replicating updates to an elastic search cluster using https://github.com/taterbase/mongoosastic, which is implemented as a plugin.   

Might be nice to be able to do this with dynamoose as well.

Again, can implement and potentially submit as a PR.

**Comment by brandongoode** [comment]
Sounds like another great idea.  Again, PR would be great.

**Comment by fishcharlie** [comment]
I'm starting to implement plugin support to Dynamoose. Trying to build this out in the open so that people can give suggestions and feedback. Feel free to comment on PR #325 with feedback or suggestions.

**Comment by mogwai** [comment]
Add this to the list of plugin ideas?

**Comment by fishcharlie** [comment]
@mogwai I think it's referenced there.
