### ISSUE TITLE
Model.delete response does not indicate successful delete

### ISSUE THREAD

**Issue by jcowley** [dynamoosejs/dynamoose#190]
I'm building a REST API and would like to return a 404 if no matching record was found.

I'm curious why the `delete` function doesn't return anything to indicate whether the delete was successful or not. If no matching record was found to delete, the function doesn't return an error (or anything else to indicate the delete failed).

I realize I can do a `get` first to see if the record exists and then another `get` after the `delete` to confirm that the delete actually worked, but that seems like a lot of extra API calls. 

Is this just a limitation of the underlying DynamoDB API?

**Comment by brandongoode** [comment]
Try using the `update` option when calling delete: `Model.delete(key, { update: true })` or `item.delete({ update: true })`.  This will return an item with the values if it exist.

**Comment by jcowley** [comment]
That works. Thank you!

**Comment by jcowley** [comment]
@brandongoode: Thanks for the tip. That indeed works. 

Is that option (or other possible `delete` options) documented anywhere? I see some options in the [API Docs](https://dynamoosejs.com/api) but not that one.

**Comment by brandongoode** [comment]
@jcowley -- Good point -- it's not.

**Comment by fishcharlie** [comment]
@brandongoode and @jcowley, create created a PR #309 to help improve the documentation around `Model.delete`. I'd love a check to ensure what I said is accurate and makes sense.

**Comment by SergiosKolios** [comment]
I am having the same issue even though I am using the option `{ update: true }`
```
const model = require('./model');

const deleteDocument = async (tableName, primaryKey) => {
    const model = await model(tableName);
    return await model.delete(primaryKey, { update: true });
}
```

Any idea what might be going on?

I am using `    "dynamoose": "^2.7.3",`

**Comment by fishcharlie** [comment]
@SergiosKolios This issue was created in 2017. Since then v2 has been released which is a complete rewrite. So strong chance this is completely unrelated to what you are talking about.

Please create a new issue for this.

Also, `update` is not a valid setting in v2 (https://dynamoosejs.com/guide/Model#modeldeletekey-settings). So there is a **chance** this is a feature request.
