### ISSUE TITLE
Typescript declaration is not up to date with API

### ISSUE THREAD

**Issue by tensult** [dynamoosejs/dynamoose#193]
https://github.com/automategreen/dynamoose/blob/aba7a4e09f91cb1a577d39bc7e81cabce6751d2b/dynamoose.d.ts#L38

https://dynamoosejs.com/api

validate: function, regular expression, or value

Validation required before for saving.

If validate is a function, the function is used to validate the attribute’s value. The function must have the signature:
```javascript
function(value, model) {
  if(valid)
    return true;
  else
    return false;
}
```
If it is a RegExp, it is compared using RegExp.text(value).

If it is a value, it is compared with ===.

**Comment by brandongoode** [comment]
PR welcome from anyone (who uses Typescript).

**Comment by fishcharlie** [comment]
@hassankhan I don't see this happening anytime soon. Myself and @brandongoode are the only collaborators of the project currently and I haven't used Typescript at all. I think the learning curve for new contributors is a massive negative for this project in it's current state.

That being said I would be open to exploring this further down the road. It would require me learning Typescript which I'm 100% ok doing for this project, but I see there being much bigger priorities that need to happen for this library before that happens.

Maybe @brandongoode will overrule me, but I don't see refactoring for Typescript happening anytime soon.

**Comment by hassankhan** [comment]
Hi @fishcharlie,

It might be an idea to only use the Typescript compiler for transpilation. This would let contributors use all the latest syntax, and frees maintainers from having to keep up-to-date with `babel` etc. I'd be willing to give it a shot in a PR, if that sounds okay?

**Comment by fishcharlie** [comment]
@hassankhan I have honestly never been a fan of transpilers. It requires **SO** much overhead, and I personally don't see the value for this project. In version 1.0 we will be dropping support for older versions of Node.js so we can start using ES6+ syntax.

The amount of overhead and extra maintenance required for the toolchain and the DevOps side of things seems like a huge cost that personally I'm not willing to bare right now.

Again, maybe @brandongoode might overrule me, but I don't see the benefit right now for it.

Also we really need more people active in maintaining this project, and I'm concerned changes in this area might increase the learning curve for getting more people involved in this project.

That all being said, I'm always open minded. So I'd like to hear more about my thoughts above and how we could manage the cons of this.
