### ISSUE TITLE
Whole batchWriteItems errors if one batch errored

### ISSUE THREAD

**Issue by ben-harris** [dynamoosejs/dynamoose#204]
If any promise in `batchList` has been rejected, [`Q.all`](https://github.com/automategreen/dynamoose/blob/fdfdfc3973e820d4c6868369ea2b9d7af120bcd4/lib/Model.js#L1155) will reject and you don't know which data has/hasn't been inserted (unlike `UnprocessedItems`).  It would be useful if it returned something like:

```
{
  Responses: {},
  UnprocessedItems: {},
  Errors: {
    MyTable: [{ /* Error & batch info */ }]
  }
}
```

Can you see any issue with that?

**Comment by brandongoode** [comment]
I can see where the current behavior is a problem.   Your idea is a good solution.  The only concern is anyone that is relying on the reject in their logic will have to update their code to check for Errors. It obfuscates the fact there was an error.

**Comment by scooper91** [comment]
I agree that the above solution obfuscates the error.  However, if `ddb().batchWriteItem()` calls back with a [`ProvisionedThroughputExceededException`](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html), the items from that request are effectively just unprocessed items.   When that happens, could the batch be somehow appended to `unprocessedItems`?

**Comment by brandongoode** [comment]
@scooper91, It may be best to keep it separate because you may need to handle it differently.  

When I think about the solution @ben-harris proposed it may be the only way not to lose the information.  Instead of Q.all we should be using Q.allSettled.
