### ISSUE TITLE
[Feature Request] Swagger -> Dynamoose schema

### ISSUE THREAD

**Issue by jonathankeebler** [dynamoosejs/dynamoose#207]
Would love to see a project like [swagger-mongoose](https://www.npmjs.com/package/swagger-mongoose) for Dynamoose. The Mongoose schema is so close to the Dynamoose schema, maybe it would work out of the box?

**Comment by brandongoode** [comment]
It wouldn't work out of the box, but you could probably fork it and replace the references to mongoose with dynamoose and be 95% working.

**Comment by fishcharlie** [comment]
Hoping this is possible with the new plugins system. Therefor migrating to the new plugin ideas repo.

https://github.com/dynamoosejs/dynamoose-plugin-ideas/issues/4
