### ISSUE TITLE
Handle retryable errors inside dynamoose?

### ISSUE THREAD

**Issue by treyhuffine** [dynamoosejs/dynamoose#209]
Would you interested in handling retryable errors inside dynamoose? I've been trying to think of a clever way to do it, but the more I think about it, the more I think it makes sense to have this as an option on a query. I think the application shouldn't be concerned about how it gets the data or how an update is made, it should just be concerned with using the result.

Let me know what you think and I can look at putting a PR together.

**Comment by brandongoode** [comment]
@treyhuffine -- First sorry for the slow response.  

I think it's  a great idea.   I've thought about the same thing before and have looked into adding some auto back-off logic when thresholds are reached.  Just never found the time to implement it.

**Comment by treyhuffine** [comment]
No worries! I'll try to have you a PR this week unless you already had something in mind

**Comment by brandongoode** [comment]
That would be great.  I don't have anything but some ideas based on AWS's document: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.RetryAndBackoff

**Comment by fishcharlie** [comment]
@treyhuffine Still interested in trying to get this done as a PR?

**Comment by lengk** [comment]
Which of the [backoff methods](https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/) would be preferred? 

Would these be configurable for each individual model, each CRUD request, or  have the option to configure it when initialising the connection?

**Comment by fishcharlie** [comment]
@lengk Maybe all 3? Give the option to set it in the dynamoose connection itself, then each model, then each request, maybe?

Another question tho. According to the [docs](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.Errors.html#Programming.Errors.RetryAndBackoff) the AWS SDKs `implement automatic retry logic and exponential backoff`. So is this even required? I just noticed that when looking through it now.

**Comment by lengk** [comment]
Yes it seems they have it as part of the SDK: 

```
maxRetries (Integer) — the maximum amount of retries to attempt with a request.

...

retryDelayOptions (map) — A set of options to configure the retry delay on retryable errors. Currently supported options are:
- base [Integer] — The base number of milliseconds to use in the exponential backoff for operation retries. Defaults to 100 ms for all services except DynamoDB, where it defaults to 50ms.
- customBackoff [function] — A custom function that accepts a retry count and returns the amount of time to delay in milliseconds. The base option will be ignored if this option is supplied.
```

**Comment by lengk** [comment]
However it implies that this algorithm doesn't implement retries: 

> If DynamoDB returns any unprocessed items, you should retry the batch operation on those items. However, we strongly recommend that you use an exponential backoff algorithm. If you retry the batch operation immediately, the underlying read or write requests can still fail due to throttling on the individual tables. If you delay the batch operation using exponential backoff, the individual requests in the batch are much more likely to succeed.
> 
> For more information, see Batch Operations and Error Handling in the Amazon DynamoDB Developer Guide.

**Comment by fishcharlie** [comment]
@lengk I know I have seen errors from Dynamoose related to capacity. So I'm not sure if that is after retries have been attempted.

**Comment by lengk** [comment]
@fishcharlie Yes I have as well. I've actually just implemented this for my program. See what happens when you increase the `maxRetries`? 

```js
dynamo.AWS.config.update({
    maxRetries: 20
})
```

**Comment by lengk** [comment]
Yes I think that documentation is needed as this seems to fix the problem. I'm still not sure whether this is the case for the `batchPut` and `batchGet` operations

**Comment by fishcharlie** [comment]
@lengk If you would like to submit a PR to update the documentation for this I would really appreciate it. Otherwise I'll get around to it when I can.

**Comment by mogwai** [comment]
Here is what I'm using.

```js
const baseBackOff = 500
const max = 10000

async function handleThroughput(model, method, backoff = baseBackOff, attempt = 1) {
    try {
        await new Promise(res => setTimeout(res, backoff))
        return await method(model)
    } catch (e) {
        if (e.code === "ProvisionedThroughputExceededException") {
            let tempt = Math.min(max, baseBackOff * Math.pow(2, attempt))
            backoff = tempt / 2 + _.random(0, tempt / 2, true)
            console.log("Backing off for " + backoff)
            return await handleThroughput(model, method, backoff, ++attempt)
        }
        else throw e
    }
}
```

**Comment by fishcharlie** [comment]
@mogwai So this looks to be more than a documentation change. Is that correct?

**Comment by mogwai** [comment]
Depends what everyone else thinks but I think this could be built in. The fact is that you will get `ProvisionedThroughputExceededException` exceptions thrown when using the batch Operation.

**Comment by mogwai** [comment]
> Here is what I'm using.

What I didn't implement is on retries, only trying again for the unproccessed items
