### ISSUE TITLE
Performing a Scan on Global Secondary Index

### ISSUE THREAD

**Issue by expatiating** [dynamoosejs/dynamoose#211]
I am trying to scan on a GSI and I am able to do this in both on the AWS CLI and AWS console, but have been unable to figure out how to do this in Dynamoose.

Is there a way to do this? I saw this issue #136 regarding using the query with `.using()` feature, but it doesn't appear that `.using()` is supported in the scan operation. 

My use case is similar to that described in the following link: [Guidelines For GSI using Sparse Indexes](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForGSI.html#GuidelinesForGSI.SparseIndexes)

**Comment by brandongoode** [comment]
First sorry for the slow response.

Scan looks at the whole table, regardless of the index.  To search a GSI, you should use `.query`.

**Comment by expatiating** [comment]
@brandongoode, thanks for your response. I was able to implement with a query. 

What is interesting though, you can perform a **scan** operation of a **sparsely populated GSI** using the AWS Dynamodb CLI and AWS console

For example:
```bash
aws dynamodb scan --index id_open_time_idx --table-name testTable
```

where `id_open_time_idx` is a sparse index. This returns only the entries from the table where the sparse index is populated and thus doesn't appear to scan the whole table.

Relevant AWS information regarding sparse index:
[AWS Guidelines For **GSI** using Sparse Indexes](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForGSI.html#GuidelinesForGSI.SparseIndexes)
 [ AWS Guidelines For **LSI** using Sparse Indexes ](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForLSI.html#GuidelinesForLSI.SparseIndexes) <--- this link actually describes my use case most closely, in my first post I specified the wrong link. :)

BTW this project is pretty awesome - thank you!

**Comment by dolsem** [comment]
@brandongoode, @fishcharlie. @expatiating is right. It is possible to scan secondary indexes in DynamoDB. Here's [another link](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.Indexes.QueryAndScan.html). It is explicitly stated in the last paragraph, _"You can also perform Scan operations on a secondary index, in the same way that you would do so on a table."_ Has this been implemented in Dynamoose yet? It's a quite valuable feature.

**Comment by fishcharlie** [comment]
@dolsem Maybe I don’t understand well enough. But what is the benefit of scanning vs querying on an index? I was always under the impression that query’s had better performance and the only reason you would use scan over query is if you didn’t have an index for the given attribute.

From my understanding there is no feature currently in Dynamoose that allows this feature. A PR would be awesome tho.

**Comment by dolsem** [comment]
@fishcharlie if you have a sparse index, the scan operation might not be that costly, depending on your data model. Moreover, I don't think there's a way to query ALL elements with query. If your data is not separated into chunks by using hash key + range key (so you use only hash key), I believe your query will always return a single element, because you need to explicitly set the value of the hash key you're querying.

**Comment by fishcharlie** [comment]
@dolsem But how would that be different than querying the table itself? I thought that all of the data from your standard table are replicated across to your indexes. So how would scanning an index produce different data than just scanning the table itself?

**Comment by expatiating** [comment]
@fishcharlie & @dolsem glad there is renewed interest in this a year later! :) 

@fishcharlie there are very efficient use cases to perform a sparse index **scan**. 
For instance, you have an ordering system and want to display on the dashboard all unfulfilled orders based on a parameter `openTimeIndex`, which you've set up as a secondary index. When the orders come in you set `openTimeIndex: <unix time stamp order came in>` (so you can sort oldest to newest as opposed to a boolean) and after you fulfill the order you set the parameter to `openTimeIndex: null`. Then in any subsequent **scan** operations on the index will not return any of the orders that are set to `null`, i.e., the index is sparse!

And the nice thing about using a sparse secondary index to do my **scan** is that I don't need to know anything about the `partition key` nor the `sort key`; all I need to know is the index.

As mentioned last year, I managed to make a query work in it's place, but it required me to add a GSI that used a fairly static parameter (location id) as the `partition key` and then my `openTimeIndex` sparsely populated parameter as the `sort key`.

Happy coding! 👨‍💻 👩‍💻

**Comment by fishcharlie** [comment]
If someone wants to try to implement this I'd be happy to review a PR.

**Comment by ydvsailendar** [comment]
um i am using query in place of scan using secondary index here is my schema `//Service Schema.
var dynamoose = require('dynamoose');

var ServiceSchema = new dynamoose.Schema({
  id: {
    type: String,
    index:{
      global: true,
      name: 'ServiceIdIndex'
    }
  },
  name : {
    hashKey: true,
    type: String
  },
  description: {
    type: String,
    default: "Once a company has access to this, he has access to all companies",
    required: true
  },
  image:{
    type: String
  },
  thumbnail : {
    type: String
  },
  cost: {
    type: Number
  },
  createdAt:{
    type: Date,
    default: Date.now
  },
  redirectUris: {
    type:[String]
  },
  enabled: {
    type: Boolean,
    required: true,
    default: false,
    index: {
      global: true,
      name: "enabledGlobalIndex"
    }
  },
  grants: {
    type: [String]
  }
});

ServiceSchema.method('getBaseFeature', async function () {
    var {Feature} = require("./index");
    var feature = await Feature.query("serviceId").eq(this.id).filter({type: "base"}).exec();  
    if (feature.length != 0)
    {
      return feature[0];
    }
    return false;
});

module.exports = ServiceSchema;` and my query is here `await Service.query("enabled").eq(true).exec();`
