### ISSUE TITLE
Any plan to integrate with DAX?

### ISSUE THREAD

**Issue by tensult** [dynamoosejs/dynamoose#212]
https://aws.amazon.com/dynamodb/dax/

**Comment by brandongoode** [comment]
Yes, but no timeline.  Amazon just released the official client a week or two ago. 

If anyone wants to create a PR for this, I would be happy to merge it.

**Comment by fishcharlie** [comment]
@ghost or @hassankhan, either of you interested in creating a PR for this?

**Comment by fishcharlie** [comment]
I created a PR for this (#330). I need some help writing some tests, improving the documentation with an example, and testing it with DAX (since I have never used DAX before). If anyone would like to help please follow the instructions on that PR.
