### ISSUE TITLE
Support for native promises (async/await)

### ISSUE THREAD

**Issue by fishcharlie** [dynamoosejs/dynamoose#216]
It would be awesome to see support for native promises, so that Dynamoose can support the new `async`/`await` syntax. It looks like according to [this post](https://medium.com/@joshuawcomeau/using-async-await-with-traditional-packages-10316d6cc4ee) one option is to wrap existing code in a native promise to make it super modular.

I know there are certain features that 3rd party promise libraries offer compared to native promises, not sure how much Dynamoose uses these features and what the pros and cons would be to implementing this. But the `async`/`await` syntax is super useful and would love to see support with Dynamoose.

**Comment by brandongoode** [comment]
Completely agree.  If you look at my first goal for 1.0 release (https://github.com/automategreen/dynamoose#release-10) it's to update to ES6.  Part of that would include native promises.

That being said, I need to find some spare time (something I'm in short supply of lately) to get around to the 0.9 list first.

**Comment by lengk** [comment]
I've been able to use most functions with the syntax

**Comment by Aedalus** [comment]
Would you be open to a PR if I tried to tackle this? I'd like to try to tackle this to remove the dependency on Q, ideally using native async/await when possible and the native util.promisify otherwise.

**Comment by fishcharlie** [comment]
@Aedalus, @mogwai is correct, `async`/`await` work currently. I'm 100% open to a PR for that tho. I would say to just keep the PR at just removing the Q dependency to start, and using the native util.promisify. I think doing a rewrite to use `async`/`await` internally would be more massive. That being said, I'm open to that PR as well, I just would like to keep PR's as small as possible so they are easier to review. If that makes sense.

**Comment by Aedalus** [comment]
So I believe I'm making good progress. Refactored a few of the `Q.defer/deferred.promise.nodeify(next)`, and all unit tests are still passing. 

However I had one gotcha that I'm still trying to figure out how I want to approach. Node throws a `UnhandledPromiseRejectionWarning` whenever a native promise isn't caught. (Same happens with Bluebird I believe). This results in `console.errors` whenever a rejected promise is created. 

Seems like there are a few ways to handle this, none of which I love.

Option 1: Explicitly add a catch handler for each thrown promise. Way too verbose imo, and seems kinda hacky
```
 function yourExportedFunction() {
     const p = promiseThatMightRejectFn(); 
     p.catch(() => {}); // add an empty catch handler
     return p;
 }
```

Option 2: Anywhere we might return/error, have a code branch to either call the cb, or return a promise. Again, too verbose imo and just spreads the problem throughout the codebase.

Option 3: Rewrite everything to be either async/await, or at least ignore callbacks and only return promises. Then when exposing each function, wrap it with the following Higher Order function to convert to callbacks on the fly. Seems like the cleanest way to go, and makes it pretty trivial to drop support for callbacks at a later date.
```
function promiseAndCallBack(func){
  // Assume function only supports promises, no cb param
  const callbackIndex = func.length
  return (...args) => {
    if(args[callbackIndex] !== undefined){
      return util.callbackify(func)(...args)
    } else {
      return func(...args)
    }
  }
}
```

I like approach #3 personally, but wanted to check in to make sure it felt like the direction you wanted the library to go before I refactored much more.

**Comment by fishcharlie** [comment]
@Aedalus Is this all internal or user facing?

**Comment by Aedalus** [comment]
This would all be internal. My goal would be to avoid having to use any util.promisify/callbackify for the end user so the API wouldn't change.

**Comment by fishcharlie** [comment]
@Aedalus That sounds good. Option 3 sounds best then. `async`/`await` will happen at some point internally for this package, so if we want to do it now, I'm fine with that. So long as it's not user facing that all sounds fine.

Wanna also look at this thread (https://github.com/dynamoosejs/dynamoose/pull/325#issuecomment-388313279)? I'm planning on working on that PR a little bit more, that is the next priority for me on this project unless of course someone volunteers and wants to help out. Would you be interested in helping out with that, or do you have any input since you are touching a lot of the callback/promise stuff?

**Comment by Aedalus** [comment]
I'm checking out the plugin architecture. Looks pretty solid to me. What are some of the use cases that you are looking to use plugins for? Also, what is the function of the 'priority' of plugins? I would expect all plugins to fire at the same time for events. Otherwise it seems more like middleware than a plugin?

Also, is there a reason to use prototype syntax over class syntax?

**Comment by Aedalus** [comment]
Just wanted to give a brief update! I've got it working on my fork over at https://github.com/Aedalus/dynamoose. I'm trying to hunt down one or two last uncaught rejected promises which are logging to std err, but otherwise everything is looking good. Hoping to have a PR in over the weekend. Tried to change the absolute least I could while removing Q, and I'm hoping to go back in a future PR and clean up to use async/await more.

**Comment by fishcharlie** [comment]
@Aedalus Sounds good! Looking forward to reviewing the PR and getting that in.

**Comment by Aedalus** [comment]
Just opened a PR here: https://github.com/dynamoosejs/dynamoose/pull/456

Please let me know if you need me to make any changes, or have any questions!

**Comment by fishcharlie** [comment]
Closing this issue due to the original question already being supported in Dynamoose.
