### ISSUE TITLE
Error adding Global Index on existing table.

### ISSUE THREAD

**Issue by ricxsar** [dynamoosejs/dynamoose#221]
Hi. Thank you for developing such a wonderful library. 

I have a existing model and production deployment on AWS. Due to updates on the application, I have to add Global Index to the existing table which is needed for the updates but I cannot due to an error:

`Error: indexes are not synchronized and update flag is set to false`

Now the application is not working at all because of the error. 

Please help me to solve the problem ASAP. 
Thanks

**Comment by brandongoode** [comment]
You'll need to either manually update the table in AWS to match the new Schema or allow Dynamoose to update it for you:

```js
dynamoose.model(name, schema, {update: true})
```

**Comment by lrcry** [comment]
Hi

I would suggest in production, set this `update` flag to `false`. This will not allow the app to accidentally try to sync the index and table structure and further separate the infrastructure from the app.

Cheers

**Comment by brandongoode** [comment]
@lrcry -- good recommendation -- probably should add a production recommendations to the documentation page.

**Comment by fishcharlie** [comment]
Due to the default of `update` being false, I don't see the need for a documentation change here. At least not an urgent matter. Might be done with a documentation rewrite.

Closing for now.
