### ISSUE TITLE
updatedAt Timestamp Only/Don't Change Under Certain Conditions

### ISSUE THREAD

**Issue by fishcharlie** [dynamoosejs/dynamoose#227]
It would be awesome to add a feature where the updatedAt property only updates or doesn't update under certain conditions. I have an attribute that often changes and I would like to enable an option for users that when this one attribute changes they can either choose to have it change the updatedAt property or not. Since I sort by the updatedAt property later on this would be super helpful.

Looks like we would have to change the following lines a bit to maybe pass in more data and enable that option.

https://github.com/automategreen/dynamoose/blob/71bf82a1103779337248ddcdf337f6d3eda32fb3/lib/Schema.js#L59
https://github.com/automategreen/dynamoose/blob/dc95809fdd409587f16f9981549d53b71738c02d/lib/Attribute.js#L314

**Comment by brandongoode** [comment]
Maybe a custom setter function could be added as an option to the timestamp.  Then you could return the current value if you didn't want it to update and Date.now() when you did. 

PS - Sorry for the slow response.
