### ISSUE TITLE
Type `Array` or `Object` not working even with useDocumentTypes

### ISSUE THREAD

**Issue by ReeSilva** [dynamoosejs/dynamoose#230]
Hey guys, hope you've been doing well.

First of all, thank you for this awesome SDK, is amazing to have something like this to work with Dynamo.

I'm having an issue to create my tables that I do not believe that is related with configuration, so I bring it to you guys.

When I try to create a table using type `Array` or `Object` it's keeping create the field with String and `JSON.stringify` on it's content.

This is my Schema:
```javascript
const schema = new dynamoose.Schema({
  ScheduledID: {
    type: String,
    required: true,
    hashKey: true,
  },
  ScheduledTime: {
    type: String,
    required: true,
    rangeKey: true,
    index: {
      global: true,
      name: 'ScheduledTimeIndex',
      project: true,
      throughput: 2,
    },
  },
  CustomerID: {
    type: String,
    required: true,
  },
  SubmissionID: {
    type: String,
    required: true,
  },
  SubmissionTimeout: {
    type: String,
    required: true,
  },
  CustomFields: {
    type: Object,
  },
  Channels: {
    type: Array,
    required: true,
  },
  InteractionID: {
    type: String,
    required: true,
  },
  RetryRule: {
    type: Array,
  },
  StepSequenceID: {
    type: String,
    required: true,
  },
  StepChannel: {
    type: String,
    required: true,
  },
  TTSVoiceType: {
    type: String,
    required: true,
  },
  TTSService: {
    type: String,
    required: true,
  },
  TTSLanguage: {
    type: String,
    required: true,
  },
  ClientContactData: {
    type: String,
    required: true,
  },
  Priority: {
    type: Boolean,
    default: false,
    required: true,
  },
}, {
  throughput: {
    read: 2,
    write: 2,
  },
  create: true,
  update: true,
  useNativeBooleans: true,
  useDocumentTypes: true,
  saveUnknown: true,
});
```

But when I create a new item it keeps creating Array and Objects as Strings. Let's take RetryRule as an example:
```javascript
  RetryRule: {
    type: Array,
  },
```

If I save it like this:
```javascript
RetryRule: [
        {
            retry: 1,
            time: 15
        },
        {
            retry: 2,
            time: 120
        }
    ],
```

This is how it got saved on Dynamo:
```javascript
"RetryRule": {
  "S": "[{\"retry\":1,\"time\":15},{\"retry\":2,\"time\":120}]"
},
```

I believe that there is nothing wrong with my schema. But, if it is, I apologize for the inconvenience and will be glad if you guys guide me through the right way.

Regards.

**Comment by lrcry** [comment]
Dynamoose supports this as it depends on the underlying AWS sdk, but I think it is not in the document.

As AWS sdk stores object as a map ('M') as per [DocumentClient](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#constructor-property) + [Schema.js in Dynamoose](https://github.com/automategreen/dynamoose/blob/master/lib/Attribute.js#L132), when saving an object, just specify the type as `Map`.

```
const dynamoose = require('dynamoose');

const Schm = dynamoose.model('Schm', {
  id: {
    type: String,
    hashKey: true
  },

  obj: {
    type: Map // instead of using Object, use Map here
  }
}, {useDocumentClient: true});

const s = new Schm({ id: String(Math.random()), obj: { foo: 'bar', bar: 'foo' } });

s.save()
```

Hope it helps ... I did not realise this until just now ...

**Comment by ReeSilva** [comment]
It doesn't work :/

It creates with the right attribute but, when I save a new item, the column remains empty.

Example: 
StepSequence.js
```
const StepSequence = dynamoose.model('StepSequence', {
  StepSequenceID: {
    type: Number,
    required: true,
    hashKey: true,
  },
  InteractionID: {
    type: String,
    required: true,
    rangeKey: true,
  },
  CustomerID: {
    type: String,
    required: true,
  },
  StepID: {
    type: String,
    required: true,
  },
  StepSequenceConditions: {
    type: Map,
    required: true,
  },
}, {
  throughput: {
    read: 2,
    write: 2,
  },
  create: true,
  update: true,
  useNativeBooleans: true,
  useDocumentTypes: true,
});
```

New item:
```
let stepSequence = new StepSequence({
  StepSequenceID: 1,
  InteractionID: 'b475d240-dea5-11e7-908f-cf9bed469e69',
  CustomerID: 'c80ca840-ba67-11e7-9614-1552d0b9332e',
  StepID: 'f4ae4040-dea5-11e7-908f-cf9bed469e69',
  StepSequenceConditions: {
    0: 2,
    1: 3,
  }
});
```

Saved item on Dynamo:
```
{
  "CustomerID": "c80ca840-ba67-11e7-9614-1552d0b9332e",
  "InteractionID": "b475d240-dea5-11e7-908f-cf9bed469e69",
  "StepID": "f4ae4040-dea5-11e7-908f-cf9bed469e69",
  "StepSequenceConditions": {},
  "StepSequenceID": 1
} 
```

And another doubt is: ok, I can use it with Map for objects. But, for arrays, how can I do?

Because actually if I try to use Array as a type it stores the item as json stringified string.

Thanks in advance.

Regards.

**Comment by ARAtlas** [comment]
I'm having the same problem as ReeSilva. The "useDocumentTypes: true" configuration option doesn't seem to make any difference. Object types are always stringified.

**Comment by pscamman** [comment]
Looking at the dynamoose code, there is only one case where useDocumentTypes is taken into consideration, and it is only a negative case (line 25 of [Attribute.js](https://github.com/automategreen/dynamoose/blob/master/lib/Attribute.js)). I took a stab at adding a positive case in a fork [here](https://github.com/pscamman/dynamoose/commit/a0e37d578ed7af246b29ffe892e17030a0b14139) to make the resulting dynamoDB types correspond to [this](https://dynamoosejs.com/api#attribute-types) table, but it crashes when I try to run it that way so there must be more to it. Unfortunately I don't know enough or have enough time to try anything else at the moment.

**Comment by pscamman** [comment]
So, I spent a little more time investigating this and this is what I've found:

You can actually provide the strings `'list'` or `'map'` for the attribute type, and Dynamoose will already do what my fork ultimately tries to do and what I believe you all are trying to do. There's a weird extra bit that needs to be done regardless, however: you must provide a corresponding `list` or `map` KEY on the attribute, which must contain a sort of mini-schema for what the inside of the given list or map should look like. And the weirdest part is that when you define the `list` key, it must be a single item array containing the type of its elements. Here are a few examples that all assume useDocumentTypes is set to true:

Array of Strings saved as a native DynamoDB List:

```
thing: {
  type: 'list',
  list: [String],
},
```

Object with three arbitrary String keys saved as a native DynamoDB Map:

```
thing: {
  type: 'map',
  map: {
    text1: String,
    text2: String,
    text3: String,
  },
```

Array with the above Object as its elements saved as a native DynamoDB List with native DynamoDB Map elements:

```
thing: {
  type: 'list',
  list: [
    {
      text1: String,
      text2: String,
      text3: String,
    },
  ],
},
```

My fork currently achieves this using Array and Object directly, but I could see it being a breaking change for anyone who unwittingly left useDocumentTypes on and currently has tables full of stringified Arrays and Objects, so I don't think it would be a good idea to merge it in (at this time at least). A better solution would be to simply update the documentation to reflect the above details, unless the explanations are already there and we've simply missed them.

**Comment by ARAtlas** [comment]
That's a good point that fixing useDocumentTypes could be a breaking change at this point. One option could be to make it parse the string like the old behavior did if a string is found. This generally seems the safest since it also guards against people turning useDocumentTypes on and off during development. Another option could be to abandon useDocumentTypes as an option, and create a new one called useDocTypes.

**Comment by bsimpson53** [comment]
I'm not very familiar with dynamodb but I've just been grappling with this too, I've noticed that this does the right thing:

```
thing: {
    text1: String,
    text2: String,
    text3: String,
},
otherthing: {
    type: String
}
```

However the 'saveUnknown' schema option is ignored below the first level

**Comment by jderose9** [comment]
> However the 'saveUnknown' schema option is ignored below the top level

This no longer seems to be the case.

I am basically trying to force all custom fields into a single nested object.
```
    CustomFields: { type: object},
```
This gets stored as a string regardless of useDocumentTypes value

```
    CustomFields: { type: 'map' },
```
This is stored as a map, but due to useDocumentTypes: true, which I wanted to keep the rest of the document from being polluted with unknown fields, the map always ends up empty.

I saw that saveUnknown can now take an array, but it is simply a white list of attribute names - it doesn't allow unknown child attributes for the passed in field names.

Is there any way currently to achieve what I am looking to do?

**Comment by fishcharlie** [comment]
Dynamoose has gone through a lot of changes recently including the release of Dynamoose version 1.0.0. Due to that I'm closing this issue for now. Please test if this is still an issue on the latest version of Dynamoose, and you still run into problems please open a new issue and fill out all the fields in the issue template so we can properly debug, and mention this issue number in the new issue.

Thanks for using Dynamoose and we look forward to helping further if needed!

---

I meant to post this earlier on this issue, but must have missed it. @jderose9's comment reminded me to do so. I do think his comment is accurate. Feel free to open a new issue if there is still a problem!

**Comment by leanderr** [comment]
This is such a common use-case. For a project of this popularity I find it hard to believe these issues stay unsolved :-(

**Comment by fishcharlie** [comment]
@leanderr How is this unresolved? As I mentioned above, I think @jderose9’s comment is correct and has successfully worked for me. What is the issue?

**Comment by leanderr** [comment]
`var testSchema = new Schema({
    address1: {
        type: 'map',
        firstName: String,
        lastName: String
    }
},

    {
        useDocumentTypes: true,
        saveUnknown: ['address1'],
    }
);

var Mod = dynamoose.model('LeadTable03', testSchema);

var concreteLead = new Mod({
    address1: {
        firstName: "fn",
        lastName: "b"
    }
});`

->  One or more parameter values were invalid: Type mismatch for key address1 expected: S actual: M

**Comment by fishcharlie** [comment]
@leanderr See https://github.com/dynamoosejs/dynamoose/issues/230#issuecomment-361412970 and the following test:

https://github.com/dynamoosejs/dynamoose/blob/e4e0eeb4e3fdee80f02d41306ed92f952510cf02/test/Schema.js#L82-L168

---

It's really hard to read your code due to the lack of good formatting, but from what I can gather you need to change your schema to the following:

```js
var testSchema = new Schema({
  address1: {
    type: 'map',
    map: {
      firstName: String,
      lastName: String
    }
  }
}, {
    useDocumentTypes: true
});
```

---

I have worked with this before with no issues at all. If you are still running into problems feel free to create a PR with a failing test case to show how it's not working and we can try to find time to  investigate further.

---

As I mentioned in https://github.com/dynamoosejs/dynamoose/issues/445#issuecomment-445836105, I think the documentation does need to be updated. But I think that is the only problem that is going on here. If you would like to work on that, feel free to submit a PR and I would be happy to review it. Otherwise it will happen when someone gets around to it.

**Comment by leanderr** [comment]
Thank you so much for your help.

```
var leadSchema = new Schema({
  address1: {
    type: 'map',
    map: {
      firstName: String,
      lastName: String
    }
  }
},
  {
    useDocumentTypes: true,
    saveUnknown: ['address1'],
  }
);

  var Lead = dynamoose.model('LeadTable03', leadSchema);

  var concreteLead = new Lead({
    address1: {
      firstName: "fn",
      lastName: "ln",
    }
  });

  await concreteLead.save()
    .then(suc => {
      console.log('Success ', suc);
    })
    .catch(err => {
      console.log('Error ', err);
    });

```

Fail Saving { ValidationException: One or more parameter values were invalid: Type mismatch for key address1 expected: S actual: M
    at Request.extractError (/var/task/node_modules/aws-sdk/lib/protocol/json.js:51:27)

Deleting "saveUnknown...." will fail as well. Also Using Combinations of 'map', 'Map', Map, 'obj', 'Obj', Object'... Working on a PR. Willing to help with further Documentation and provide more examples...

**Comment by fishcharlie** [comment]
@leanderr Oh that is for sure your problem I think. In Dynamoose you can’t combine types. Especially with the “saveUnknown” property. Just won’t work. The whole point of Dynamoose is having strict typing for Dynamoose. So yes, it will fail if you are trying to use multiple types for one property.

**Comment by fishcharlie** [comment]
@leanderr You said:

> Also Using Combinations of 'map', 'Map', Map, 'obj', 'Obj', Object'

I assume that means your table looks something like the following:

```
[
  {
    address1: {
       S: '{firstname: "Test", lastname: "User"}'
    }
  },
  {
    address1: {
      M: {
        firstname: {S: "Other"},
        lastname: {S: "User"}
      }
    }
  }
]
```

(hopefully I got my syntax and everything correct)

---

^ that is not allowed in Dynamoose. You can't have one document property be a string, and another be a map. In Dynamoose currently, a `map` is different than an `object`. That is something I find very confusing and took me a while to wrap my head around. I think we should consider changing that in the future (it would be a breaking release), but that is WAY long term I think, and not something I'm prioritizing now. The priority now is updating the documentation. If someone wants to take on a rewrite of this system, I'd be very open to that.

In the example above the first option is an `object`. And the second is a `map`.

---

Hopefully that makes sense.

--- 

> Do you mean you cannot have an Object that has attributes of e.g. String and NUmber?

If I understand correctly, you can.

> Are there any working examples with Maps or Arrays of Maps at all?

Yes. In my previous comment I linked you to a test that we are using to test this functionality.

**Comment by leanderr** [comment]
The tested example you provided in dynamoose/test/Schema.js will save the Map as a String to the Database...

```
var schema = new Schema({
  id: {
    type: Number,
    //  validate: function(v) { return v > 0; }, 
    rangeKey: true
  },
  breed: {
    type: String,
    hashKey: true
  },
  aMap: {
    type: 'map',
    map: {
      mapId: { type: Number, required: true },
      mapName: { type: String, required: true }
    }
  },
  //  aList: { 
  //    type: 'list', 
  //    list: [ 
  //      { 
  //        listMapId: {type: Number, default: 1}, 
  //        listMapName: {type: String, default:"SomeName"} 
  //      } 
  //    ] 
  //  } 
}, { throughput: { read: 10, write: 2 }, useDocumentTypes: false, useNativeBooleans: false });

  var concreteLead = new Schem({
    id: 1,
    breed: "str",
    aMap: {
      mapId: 2424,
      mapName: "selfihsef"
    }


  });

  await concreteLead.save()

```
Saves each map as Strings into the DB

**Comment by jderose9** [comment]
@leanderr That's because you have useDocumentTypes: false. As per the doc, the default type for arrays and objects is 'S' unless useDocumentTypes: true.

https://dynamoosejs.com/api#attribute-types

**Comment by barroyo** [comment]
In case someone is trying to use a more complex data structure and wanted to make sure is stored keeping the same types in dynamodb and where the elements of the map also be stored as dynamic objects that ( you don't know their structure), I was able to workaround this like this: 

```
let sampleSchema = new dynamoose.Schema(
    {
        name: {
            type: String,
            required: true,
        },
        cells: {
            type: 'list',
            list: [
                {
                    name: { type: String },
                    includes: {
                        type: Object,
                    },
                    excludes: {
                        type: Object,
                    },
                },
            ],
        },
    },
    {
        useDocumentTypes: false,
    }
)
```
