### ISSUE TITLE
Support to enum attribute

### ISSUE THREAD

**Issue by Onnion** [dynamoosejs/dynamoose#239]
I'm new to dynamoDB, I'm trying to migrate from mongoDB (mongoose) to dynamoDB (dynamoose).
I came across some difficulties, one of them was the use of enum.
I did not find support in the dynamoose documentation.
Is there an alternative?

```javascript
//Example Schema in mongoose
var breakfastSchema = new Schema({
      drink: {
        type: String,
        enum: ['Coffee', 'Tea']
      }
})
```

**Comment by brandongoode** [comment]
We don't support enum (probably should).  You could use a custom validate function to verify the value matches.  This is what mongoose is doing automatically.

```js
var breakfastSchema = new Schema({
      drink: {
        type: String,
        validate: function(v) {
          let enum = ['Coffee', 'Tea']
          return undefined === v || ~enum.indexOf(v);
        }
      }
})
```

**Comment by Onnion** [comment]
Works perfect, good solution, thank you
