### ISSUE TITLE
Options for enable Dynamodb Stream when create or update table

### ISSUE THREAD

**Issue by trunglb** [dynamoosejs/dynamoose#241]
as AWS provides DynamoDB Stream options for update table, I think they also support create table with `StreamSpecification` option too:

http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateTable.html#DDB-UpdateTable-request-StreamSpecification

I would be very grateful if we have a plan for it. Thank you for your great work ! 👍

**Comment by brandongoode** [comment]
Should be pretty easy to add.

**Comment by Chrisissorry** [comment]
Did this get lost in v2?

**Comment by fishcharlie** [comment]
@Chrisissorry It did 😢. Feel free to create a new issue for this. I closed all issues as part of v2 since it was a complete rewrite.

**Comment by Chrisissorry** [comment]
@fishcharlie Done https://github.com/dynamoose/dynamoose/issues/1454
