### ISSUE TITLE
Documented and promisified middleware

### ISSUE THREAD

**Issue by jacintoArias** [dynamoosejs/dynamoose#244]
Hi,

I was going to propose the addition of moongose-like middleware to enable complex validation and so, when I saw that it has already been included in a previous PR #9, however this feature is not documented properly, and can only be reversed engineered from the code (in fact the middleware is hooked into the model object and not the schema as in mongoose).

I could help document this.

Another point is that using hooks interferes with the promisified version of the methods, at least for a previous example which was working previously.

```
var dynamoose = require('dynamoose');
dynamoose.AWS.config.update({
  region: 'eu-west-1',
});
dynamoose.local();

var catSchema = { id: Number, name: String };

var Cat = dynamoose.model('Cat', catSchema);

Cat.pre('save', function (next) {
    console.log('Middleware!');
    next();
});

Cat.create({ id: 0, name: 'sylvester' }, {}, function(err, res) {
    console.log(res);
});

Cat.create({ id: 1, name: 'garfield'  })
    .then(res => console.log(res))

```

It prints 

```
Middleware!
NewModel { id: 0, name: 'sylvester' }

TypeError: Cannot read property 'then' of undefined
...
```

I'm looking into it, but perhaps you can identify the problem quicker.

Cheers

**Comment by brandongoode** [comment]
@jacintoArias -- I could really use some help getting this polished.  It's been on my todo list for a long time and I can't ever find the time to work on it.    I put it on the roadmap for 0.9 in hope that would force me to get it done. 

I think the error is because you need to `return next()` in the plugin to return the promise.

**Comment by brandongoode** [comment]
The `return next()` is not correct.  After some more research we may need to update to `hooks-fixed` -
 https://github.com/vkarpov15/hooks-fixed

**Comment by jacintoArias** [comment]
Returning the callback fixes it, but it seems like an odd behaviour..., this plugin system really needs a good design rework, specially if the main objective is to make this package as similar as posible to mongoose. 

I can help you, just let me know where do you need the focus. In the meantime I will study the source a little bit further.

**Comment by fishcharlie** [comment]
Closed in #325

**Comment by Kaitohooi** [comment]
@jacintoArias  @brandongoode, Can I have the documentation of Dynamoose middleware? I didn't find it in the version 4 doc.

**Comment by fishcharlie** [comment]
https://github.com/dynamoose/dynamoose/discussions/1663#discussioncomment-8419553
