### ISSUE TITLE
Provide more detail in roadmap

### ISSUE THREAD

**Issue by fishcharlie** [dynamoosejs/dynamoose#249]
@brandongoode it would be awesome if you could provide more details about the roadmap. I would love to start submitting some pull requests for some of the 0.9 todo items and 1.0 todo items, but I'm unsure how you are envisioning some of those features and some don't provide enough detail to where the community can start working on them.

The more detail that can be provided the more I might be able to help with some of those items.

Maybe issues for each of those tasks with more detail and link them to the readme so I can start working on them?

**Comment by brandongoode** [comment]
ya -- I need to spend some time mapping them out a little better.  The roadmap is more of highlevel reminders for me.  I think creating issues with some checklists would be the best option.  I'll try to set aside some time over the next week to get started on some for 0.9.

**Comment by brandongoode** [comment]
@fishcharlie  - Check out #137 for some ideas on `.populate`
