### ISSUE TITLE
SaveUnknown on a per attribute basis

### ISSUE THREAD

**Issue by ro-savage** [dynamoosejs/dynamoose#275]
I'd like to save data from an external provider into our table.

Since the data isn't managed by us and I don't know what it looks like, I've had to enable `saveUnknown: true` to the entire table (alternative is stringify and save a string).

Ideally I'd be able to turn on `saveUnknown` this just for a single attribute.

Is this currently possible? If not, would you be interested in a PR to add this feature?

**Comment by fishcharlie** [comment]
@ro-savage This is not currently possible. Always love PR's to help improve Dynamoose!!
