### ISSUE TITLE
Improving error handling

### ISSUE THREAD

**Issue by ro-savage** [dynamoosejs/dynamoose#281]
Its quite common for someone in my team to run into an error like

```
err SyntaxError: Unexpected token N in JSON at position 0
    at parse (<anonymous>)
    at dedynamofy (/Users/Ro/www/passphere/lambda-api/node_modules/dynamoose/lib/Attribute.js:430:14)
 ...
```
In this case it comes from using JSON.parse on NaN (when it was expecting a number).

It would be great to throw a more useful error such as
```
err ModelError {
  name: 'ModelError',
  message: 'Attribute "total" of type "N" has an invalid value of "NaN"' }
```

I got this by wrapping `dedynamofy` in `Attribute` with a `try catch`.

There might be a better place to catch these errors, I didn't dive to deep.

Are you interested in a PR for this? Where would you like to catch the error and is `ModelError` the correct error to throw?

**Comment by fishcharlie** [comment]
@ro-savage Sorry for the delay in anyone getting back to you. PR would be great for this. I personally can't think of a better error than `ModelError`. It could be a problem with the data as well tho. Maybe `ParseError`?? I'm not sure if I have major opinions either way. Anything more similar to the proposed new error would be better than the current.

In my opinion that sounds like the correct place to wrap it with a `try catch`. But I haven't looked through it quite enough to know for sure. From my knowledge of this package that sounds correct tho.

Looking forward to a PR!

**Comment by fishcharlie** [comment]
@ro-savage Maybe this is also similar to #182

**Comment by fishcharlie** [comment]
@ro-savage, I submitted a PR #331 that tries to improve this. Let me know your thoughts on it.

**Comment by ro-savage** [comment]
@fishcharlie - Looks great Charlie. Exactly what is needed.

Got caught by this again today, searching through trying to find what field is throwing the error. This would save heaps of time.
