### ISSUE TITLE
Support for "SSESpecification" Schema option

### ISSUE THREAD

**Issue by chaleCB** [dynamoosejs/dynamoose#283]
DynamoDB [recently announced server-side encryption](https://aws.amazon.com/blogs/aws/new-encryption-at-rest-for-dynamodb), and it would be great if we could enable it when creating a table via the Dynamoose Schema options.. or at the very least, supply a way for users to pass-through additional options that aren't parsed by the Dynamoose API.

**Comment by RobertNorthard** [comment]
+1 I'm also very interested in this feature.

**Comment by fishcharlie** [comment]
If anyone would like to create a PR for this I would be happy to review it and try to get it merged in.

**Comment by fishcharlie** [comment]
@chaleCB and @RobertNorthard, I created a PR #306 for this feature. Just tested it and it seems to be working pretty well. You can either take my branch on my fork until we get this into a Dynamoose version or just wait until we get it added.

Would love to hear any input you have on it as well.

I will be keeping the PR open for a little bit just so I can try to figure out why that one test case isn't working and how I can fix it.
