### ISSUE TITLE
No Documentation on What IAM Permissions are Required

### ISSUE THREAD

**Issue by chrisguitarguy** [dynamoosejs/dynamoose#292]
Would be great if the docs could include some IAM policy samples on what sorts of permissions are required:

1. To read (no creation or updates)
2. To create the tables
3. To update the tables

There are pre-made policies in AWS for dynamo, but they are often really permissive.

**Comment by fishcharlie** [comment]
@chrisguitarguy Feel free to create a PR and I would be happy to take a look at it. Otherwise I'll try to get around to it at some point.
