### ISSUE TITLE
Nested Schemas/Models

### ISSUE THREAD

**Issue by fishcharlie** [dynamoosejs/dynamoose#301]
Dynamoose should support the following.

```
var productsSchema = new dynamoose.Schema({
	_id: String,
	name: String
});
module.exports = productsSchema;


var userSchema = new dynamoose.Schema({
	_id: String,
	firstname: String,
	lastname: String,
	email: String,
	password: String,
        products: [productsSchema]
}, {
	timestamps: true
});
module.exports = dynamoose.model('myProject_User', userSchema);
```

OR

```
var productsSchema = new dynamoose.Schema({
	_id: String,
	name: String
});
module.exports = productsSchema;


var userSchema = new dynamoose.Schema({
	_id: String,
	firstname: String,
	lastname: String,
	email: String,
	password: String,
        myProduct: productsSchema
}, {
	timestamps: true
});
module.exports = dynamoose.model('myProject_User', userSchema);
```

**Comment by fishcharlie** [comment]
Then you could create it by doing the following.

```
var Product = require("...")
var User = require("...")

var myProduct = new Product({_id: "item1", name: "Computer"});
var myUser = new User({_id: "user1", product: [myProduct]});
```

OR

```
var Product = require("...")
var User = require("...")

var product = new Product({_id: "item1", name: "Computer"});
var myUser = new User({_id: "user1", myProduct: product});
```

**Comment by fishcharlie** [comment]
I might take a stab at submitting a pull request to integrate this if I have time. Any tips, suggestions, pointers, things I need to watch out for, thoughts on how to integrate would be super helpful.

**Comment by fishcharlie** [comment]
See PR #329 for this.

**Comment by Euklidian-Space** [comment]
Hey @fishcharlie I would like to take a crack at this if that's cool.  Got a question though.  I would like to run just one test file.  I am trying to get familiar with the inner workings of model and schema by doing discovery testing, but it is time consuming to run the whole test suite.  

Thanks,
ES

**Comment by fishcharlie** [comment]
@Euklidian-Space That'd be awesome!! I saw a schema like the following before, but I don't know if it'd work.

```
var UserSchema = new dynamoose.Schema({
	userId: {
		hashKey: true,
		type: String
	},
	creationTime: {
		rangeKey: true,
		type: Number
	},
	first_name: {
		type: String
	},
	last_name: {
		type: String
	},
	device_info: [{
		device_id: {
			type: String,
			default: null
		},
		access_token: {
			type: String,
			default: null
		}
	}],
	is_active: {
		type: Boolean,
		default: true
	},
	blogs: []
}, {
	useNativeBooleans: true,
	useDocumentTypes: true,
	timestamps: {
		createdAt: 'creation_at',
		updatedAt: 'updated_at'
	}
});
```

That might be something to look at.

In order to run one test or one section of tests you can change `it` to `it.only` **OR** `describe` to `describe.only` and that will only run those tests.

I think you should be able to just create a fork off of my fork I created here. Keep me posted and let me know if you have any questions!! Looking forward to seeing what you come up with! 😃

**Comment by fishcharlie** [comment]
@Euklidian-Space I forgot to mention. I created test cases in PR #329. I'd also look into issue #180. All the details I have found related to this so far are split between this issue and PR #329. Everything (including related issues) should be listed in one of the two places.

**Comment by Euklidian-Space** [comment]
Hey @fishcharlie in what sense do nested schemas don't work?  All of my checks are passing.  I even tried the shema you posted.  Here is my code,

var User = dynamoose.model("my_user", UserSchema);
  var device_info = [{
    device_id: "device1",
    access_token: "token1"
  }];

  var user1 = new User({userId: "user1", first_name: "bob", device_info: device_info});

When I log out user1 I get the following,

Model-my_user {
  userId: 'user1',
  first_name: 'bob',
  device_info: [ { device_id: 'device1', access_token: 'token1' } ] }

That is what we want no?

**Comment by fishcharlie** [comment]
@Euklidian-Space Do you think we should add support for getting the test cases I wrote working? At the very least I think our documentation could be more clear about this.

**Comment by Euklidian-Space** [comment]
@fishcharlie  I got your subschemas branch on my local machine.  Gonna comb over the test cases and see what I can find.

**Comment by meszaros-lajos-gyorgy** [comment]
Hi! Is there any progress on this? Are there any temporary solutions to achieve at least partial support for nested schemas? Thanks!

**Comment by meszaros-lajos-gyorgy** [comment]
okay, I'll just use Postgres or Mongo then...

**Comment by fishcharlie** [comment]
@meszaros-lajos-gyorgy Sorry for the delayed reply. This got lost in my email. Take a look at #445 #446, and this comment: https://github.com/dynamoosejs/dynamoose/issues/230#issuecomment-445903933.

There are ways to have a structured object or array in Dynamoose while preserving the schema.

Overall beyond those comments and links, I don't have anything else to share at this time. This is semi low priority for right this second. I did add it to the #560 release planning ticket.

Also, this is open source, so if you want to contribute by submitting PR's that would be awesome!

**Comment by meszaros-lajos-gyorgy** [comment]
Thanks for the reply, I'll check out the discussion in the pages you've linked!

**Comment by fishcharlie** [comment]
@meszaros-lajos-gyorgy Awesome! Good luck!!

**Comment by softmarshmallow** [comment]
relating https://github.com/dynamoose/dynamoose/issues/1047 , https://github.com/dynamoose/dynamoose/issues/1043
