### ISSUE TITLE
Async Set, validate

### ISSUE THREAD

**Issue by traubo279** [dynamoosejs/dynamoose#313]
It would be nice to have async / await or Promise resolve before writing to database, this save time to validate existing or write password

**Comment by fishcharlie** [comment]
Can you show an example of what you mean? Not quite following.

**Comment by traubo279** [comment]
Sorry, some thing like this would be nice, before set to database, we can encrypt the password
>     password: {
>         type: String,
>         validate: password => validator.isLength( password , { min: 6 }) && (password.match(/\d/g) != null),
>         set: async password => await cryptPassword(password),
>         required: true
>     },

**Comment by fishcharlie** [comment]
Oh I get it now. Great suggestion! If you want to submit a PR feel free and we can get it integrated. Otherwise I’m not sure when we’ll be able to get it added but we’ll for sure keep it on the list of todos.

**Comment by fishcharlie** [comment]
The one thing we have to remember about this is currently Dynamoose still supports Node 0.12. So that might make adding this a bit more difficult.

**Comment by traubo279** [comment]
@fishcharlie Would u consider have a NEXT branch ? i could rewrite it with new standard ..

**Comment by fishcharlie** [comment]
Yes. If you create a PR and mention that in the message I can change the branch to merge into to a new next branch after you submit the PR.

**Comment by fishcharlie** [comment]
@traubo279 As of v1.0 Dynamoose will support Node.js versions >8. If you would like to create a PR for this, we can get it merged in. Otherwise I'll try to get around to it at some point.

**Comment by traubo279** [comment]
@fishcharlie Sorry for the late reply, i'm longer active on any aws project, so i'm lazy to re-setup test environment again. Generally, since each model put/update/etc resolve "schema.toDynamo" and called chain toDynamo from Attributes. To implement async, it involve wrapping all the code into a .then method. Which i think its quite messy to support a nice to have function.

**Comment by fishcharlie** [comment]
@traubo279 I think we could implement this using the `await` feature. I'm going to reopen this so we can keep track of it.

**Comment by traubo279** [comment]
@fishcharlie Yes, i thought of es6 await originally, but i have no access to current dev branch 1.0. Happy to contribute here if you need ..

**Comment by fishcharlie** [comment]
@traubo279 Submit a PR to the master branch 😃, v1.0 is coming after the test in #376 is fixed. So all v1.0 changes are hitting the master branch right now.

**Comment by yoitsro** [comment]
Hey! If possible, could the API for defining async validators be the same as mongoose's? https://mongoosejs.com/docs/validation.html#async-custom-validators

This would ensure things like [Joigoose](https://github.com/yoitsro/joigoose) are still compatible with dynagoose.

**Comment by fishcharlie** [comment]
@yoitsro I'm not sure that would be compatible even if the API was the same. It could be, but at first glance I doubt it. If you wanna submit a PR for this, I'd be more than happy to review it. But if you don't submit a PR for it, I can't guarantee that it will use the same API as mongoose's. But I think it would be a nice goal to have.

**Comment by yoitsro** [comment]
Thanks for that @fishcharlie. @japier initially raised the issue here https://github.com/yoitsro/joigoose/issues/23

@japier, how would you feel about giving this a shot?

**Comment by fishcharlie** [comment]
@yoitsro I didn't realized you maintain the Joigoose project until just now. I would be more than happy to work on this so long as you are available to review a potential PR and ensure that it fits with your project.

**Comment by fishcharlie** [comment]
Just opened a PR for this @yoitsro. Still need to add support for some of the other schema method options. But after it's complete I will ping you on that PR and maybe you can review it and let me know if you have any suggestions about how I did things, and if you think it'll work with your project.

#492

**Comment by fishcharlie** [comment]
@yoitsro This will not be fully compatible with your project. I will attempt to get it as close as possible. But we are currently passing the model in as the 2nd parameter to the function, so for the callback solution, it will have to be the 3rd parameter.

**Comment by yoitsro** [comment]
Quite the dilemma! I _could_ try and do something to determine whether the user is using Mongoose or Dynagoose and determine which parameters should be where, but this feels kinda hacky.

The alternative would be to have a configuration option which the user would have to manually specify. This feels better but is still not an ideal solution.

I know this doesn't directly concern you, but your opinion would be helpful 😄

**Comment by fishcharlie** [comment]
@yoitsro I feel like trying to determine if it's Mongoose or Dynamoose would be best. I could also add an option to `disableModelParameter` which would default to `false`, but you could set it to `true`, if that would help you.

Let me know what would be best for you.

I still have the goal of getting this to work. Obviously a Dynamoose user wants it. So trying to provide what I can to help make it work is something I'm trying to do. 😃

**Comment by yoitsro** [comment]
I can see the benefit of modifying in Dynamoose as it'll mean compatibility with other packages related to Mongoose validation will also work with Dynamoose.

Would adding the `disableModelParameter` option cause any significant adverse effects for you?

**Comment by fishcharlie** [comment]
@yoitsro I think that should be fine. I'll ping you on that PR when I'm ready for you to take a look at it and review compatibility.
