### ISSUE TITLE
Table index not selected correctly when querying

### ISSUE THREAD

**Issue by ricxsar** [dynamoosejs/dynamoose#343]
I have a table `ScheduleLog` with 2 global indexes using the same primary key `orgId` and different range keys `createdAt`, `expectedArriveAt` . See schema below:
```
const schema = new Schema({
	id: {
		type    : String,
		hashKey : true,
		default : uuid.v1,
		required: true
	},
	orgId: {
		type    : String,
		index: [
		{
			global    : true,
			name      : 'OrganizationCreateAtIndex',
			rangeKey  : 'createdAt',
			throughput: 1
	       },
	       {
			global    : true,
			name      : 'OrganizationExpectedArriveAtIndex',
			rangeKey  : 'expectedArriveAt',
			throughput: 1
	       }],		
	       required: true,
	},
	assetId: {
		type    : String,
		required: true,
		index: {
			global    : true,
			name      : 'AssetIndex',
			rangeKey: 'createdAt',
			throughput: 1
	        },
	},
	scheduleId: {
		type    : String,
		required: true
	},
	status: {
		type    : String,
		default	: "QUEUED",
		required: true
	},
	origin: {
		type    : Object,
		required: true	
	},
	destination: {
		type    : Object,
		required: true
	},
	distance: {
		type    : Number
	},
	expectedDepartAt: {
		type    : Date,
		default : Date.now,
		required: true
	},
	actualDepartAt: {
		type    : Date
	},
	expectedArriveAt: {
		type    : Date,
		default : Date.now,
		required: true	
	},
	actualArriveAt: {
		type    : Date
	},
	time_minutes: {	// minutes
		type    : Number,
	},
	tracepoints: {
		type    : [String],
		default : [],
	},
	remarks: {
		type    : String
	}
},{
	throughput: 1,
	timestamps: true
});
```

When I query the table using the primary key `orgId` and range key `expectedArriveAt`, the `OrganizationCreateAtIndex` is used not the `OrganizationExpectedArriveAtIndex`. See complete query 
 and error below:
```
ScheduleLog.query('orgId').eq("b76e5930-5c79-11e7-917a-fd1a3417d363")
.where('expectedArriveAt').lt( new Date() )
.exec()
.then(function(res){
	console.log(res);
})
.catch(function(e){
	console.log(e)
})
```
```
{ [ValidationException: Query condition missed key schema element: createdAt]
  message: 'Query condition missed key schema element: createdAt',
  code: 'ValidationException',
  time: Fri Apr 20 2018 06:23:37 GMT+0000 (UTC),
  requestId: 'SM16CHILVIVAV418C99062NTFNVV4KQNSO5AEMVJF66Q9ASUAAJG',
  statusCode: 400,
  retryable: false,
  retryDelay: 25.108835729770362 }
```
I hope this will be fixed asap. Thanks.

**Comment by fishcharlie** [comment]
@ricxsar I created a PR creating a test case for this (#344). I'm not sure when we will be able to get around to fixing this. I'm aiming to get this fixed before version 0.9. But any help fixing this would be much appreciated and help speed everything up.

**Comment by ricxsar** [comment]
Sorry @fishcharlie but I don't have spare time at the moment. Is there any way to hint query to use a particular index like `using("index name")` or something so that we can move on to my development?

**Comment by fishcharlie** [comment]
@ricxsar I haven't gone in depth to how Dynamoose/DynamoDB handles that. I'm guessing that functionality would be pretty easy, but I'm not 100% sure. I'll see if I can find some time to take a look this week. No promises tho.

**Comment by ricxsar** [comment]
@fishcharlie I think this https://github.com/automategreen/dynamoose/blob/d25b045050f9a54bf646fb7f89c531a6e21e16fa/lib/Query.js#L94 should also check for the range key.

**Comment by ricxsar** [comment]
And also this one https://github.com/automategreen/dynamoose/blob/d25b045050f9a54bf646fb7f89c531a6e21e16fa/lib/Query.js#L117
There's also a possibility that an index don't contain a range key.
There's a functionality that override the index but it is not documented on the api. I don't know if this works but I will give it a try.
https://github.com/automategreen/dynamoose/blob/d25b045050f9a54bf646fb7f89c531a6e21e16fa/lib/Query.js#L144

**Comment by fishcharlie** [comment]
So I changed line 94 to the following.

    if(index.name === this.query.hashKey.name && (!this.query.rangeKey || index.rangeKey === this.query.rangeKey)) {

But now I'm getting an error on line `if(!queryReq.IndexName && schema.rangeKey.name !== rangeKey.name) {` where `schema.rangeKey` is undefined.

**Comment by ricxsar** [comment]
@fishcharlie I was able to confirm that we can override the index being used when querying. See query below:
```
ScheduleLog.query('orgId', {indexName: "OrganizationExpectedArriveAtIndex"}).eq("b76e5930-5c79-11e7-917a-fd1a3417d363")
.where('expectedArriveAt').lt( new Date() )
.exec()
.then(function(res){
	console.log(res);
})
.catch(function(e){
	console.log(e)
})
```
However we still need to fix the bug that it should select the correct index to be used automatically.

**Comment by ricxsar** [comment]
@fishcharlie I have test the PR, so far it solves the issue. Thanks for the quick solution.

**Comment by fishcharlie** [comment]
@ricxsar Thanks for testing!!

**Comment by TusharDixit** [comment]
can anyone please explain me the use of throughput and project keywords in index ??
