### ISSUE TITLE
Use DynamoDB Marshaller instead of custom logic in `Attribute`

### ISSUE THREAD

**Issue by hassankhan** [dynamoosejs/dynamoose#348]
Instead of having to maintain custom logic, we could reuse the [`Converter`](https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/converter.js) object from `DynamoDB` in `aws-sdk`.

This would help in reducing maintenance burden as well as simplify the codebase considerably.

**Comment by fishcharlie** [comment]
@hassankhan A PR for this would be awesome!!

**Comment by ecwyne** [comment]
In general I love this, however I see two issues up front.

1. Behavior is somewhat like `useDocumentTypes` is always set to `true` (always makes `Map`s and `BOOL`s)
2. `Converter.input(new Date())` -> `{ M: {} }`
