### ISSUE TITLE
Inconsistent overwrite value

### ISSUE THREAD

**Issue by ecwyne** [dynamoosejs/dynamoose#359]
`model.put` [defaults to true](https://github.com/automategreen/dynamoose/blob/master/lib/Model.js#L284)

`Model.create` [defaults to false](https://github.com/automategreen/dynamoose/blob/master/lib/Model.js#L333)

Typescript docs say that it [defaults to true](https://github.com/automategreen/dynamoose/blob/master/dynamoose.d.ts#L136-L138)

**Comment by fishcharlie** [comment]
@ecwyne Thanks for this. We'll address it in version 1.0, since it will be a breaking change.

**Comment by fishcharlie** [comment]
Thanks for this @ecwyne. I have decided to just update the TypeScript notes and keep the defaults as is.
