### ISSUE TITLE
https://dynamoosejs.com is down

### ISSUE THREAD

**Issue by SteleA** [dynamoosejs/dynamoose#368]
https://dynamoosejs.com is showing a 404 page

**Comment by fishcharlie** [comment]
@brandongoode needs to take care of this since he owns the domain name

**Comment by fishcharlie** [comment]
I'm guessing this is related to transferring the repo to a dedicated org.

**Comment by brandongoode** [comment]
I'm working on fixing this.  Yes the transfer caused the issue.  I'm waiting on AWS cloudfront push the changes to their edge nodes.

Sorry for not fixing this earlier. My 6 year old macbook's died :-( (GPU failure) and I've been working to get a replacement restored all day.

**Comment by brandongoode** [comment]
Finally think I've figured out what's wrong.  Github changed how it handles HTTPS recently.  The old repo was still using the old method.  When we transferred, it changed the settings.  The site is back up with HTTPS.  I'm working to get it working with HTTPS now.

**Comment by brandongoode** [comment]
I think it should be working now.  Please re-open this issue if it's still not working.
