### ISSUE TITLE
BatchGet model with range key with false-y value fails

### ISSUE THREAD

**Issue by haolinj** [dynamoosejs/dynamoose#378]
This is related to issue #177 that Get model with range key 0 will fail due to the false-y check. The BatchGet model has the same issue, the line that does the check:

https://github.com/dynamoosejs/dynamoose/blob/master/lib/Model.js#L1059

If range key is 0, `Range key required` error will throw.

**Comment by fishcharlie** [comment]
@haolinj If you want to create a PR for this that would be awesome!

**Comment by haolinj** [comment]
@fishcharlie Yes, PR is created.
