### ISSUE TITLE
Cannot connect to local dynamodb 

### ISSUE THREAD

**Issue by duxing** [dynamoosejs/dynamoose#380]
hi all,
I'm setting up a node js application to access dynamodb and I'm having problem connecting to my local dynamodb.

local dynamo db is running fine on port 8000:
```
aws dynamodb list-tables --endpoint-url http://0.0.0.0:8000 --output json

{
    "TableNames": []
}
```

And my simple application is identical to the given example:
https://dynamoosejs.com/examples#simple-example

when I start the script with:
```
var dynamoose = require('dynamoose');
dynamoose.local();

var Cat = dynamoose.model('Cat', { id: Number, name: String });
// the remaining example
```
I got an error message complaining region is not configured.

so I added region:
```
var dynamoose = require('dynamoose');
dynamoose.AWS.config.update({
  region: 'us-west-1'
});
dynamoose.local();

var Cat = dynamoose.model('Cat', { id: Number, name: String });
// the remaining example
```
and I got a missing credential exception. to be honest I don't understand why credentials are needed for local dynamodb access to begin with, but I would like to get around it for now.

so I passed in credentials from `~/.aws/credential`:
```
var dynamoose = require('dynamoose');
dynamoose.AWS.config.update({
  accessKeyId: '***access*key***',
  secretAccessKey: '***secret***',
  region: 'us-west-1'
});
dynamoose.local();

var Cat = dynamoose.model('Cat', { id: Number, name: String });
// the remaining example
```
and this time I got connection refused:
```
/opt/app/node_modules/dynamoose/node_modules/q/q.js:155
                throw e;
                      ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1012:19)
```

**Comment by duxing** [comment]
issue is caused by wrong local url under docker network.

**Comment by aecorredor** [comment]
@duxing I'm getting the same `ECONNREFUSED` when using `docker-compose` with a node container and a dynamodb container. How did you end up solving it? My db is also running fine locally and I map it from port 8042 on my machine to port 8000 on the container. But, the node api fails to connect.

**Comment by aecorredor** [comment]
I solved this by using the actual docker-compose service name as the endpoint and attaching the port like so: `dynamodb:8080` where `dynamodb` is the service name in docker-compose.yml. Now I'm running into this issue:

```
graphql_1   | Error: write EPROTO 140496032673096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:
graphql_1   | 
graphql_1   |     at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16) {
graphql_1   |   message: 'write EPROTO 140496032673096:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:332:\n',
graphql_1   |   errno: 'EPROTO',
graphql_1   |   code: 'NetworkingError',
graphql_1   |   syscall: 'write',
graphql_1   |   region: 'us-east-1',
graphql_1   |   hostname: 'dynamodb',
graphql_1   |   retryable: true,
graphql_1   |   time: 2020-03-27T17:54:01.378Z
graphql_1   | }
```

`graphql_1` is just my other docker container running the actual app.

**Comment by aecorredor** [comment]
Ok, I wasn't able to use `dynamoose.local`, instead I just used the AWS.DynamoDB constructor and had to pass it `sslEnabled: false` when developing locally to make it work.

**Comment by fishcharlie** [comment]
@aecorredor You using v1 or v2?

If you wanna update the global object you should be able to pass in `{sslEnabled: false}` into `dynamoose.aws.sdk.config.update` for v2, or `dynamoose.AWS.config.update` for v1. Then using the dynamoose local command should work.

But your solution works also! Glad you got it sorted out.

**Comment by aecorredor** [comment]
@fishcharlie awesome, I’m on v1 still. But glad to know that would also work. Thanks!
