### ISSUE TITLE
Trying to save a new Model with create:true fails

### ISSUE THREAD

**Issue by warnero** [dynamoosejs/dynamoose#385]
I've tried just about everything I can think of but I can't get my new object/table to correctly create the table in my local database. I can create it through the DynamoDB shell, but then I'm missing a lot of info that's in my schema.

I tried calling .getTableReq() on the Model class but that failed saying there is no such method (and I can't find it searching through the code either). Reading and reading through the docs I can't see what could be the cause of this.

Application.js
```
import dynamoose from 'dynamoose'

let options = {
    useDocumentTypes: false,
    useNativeBooleans: false,
    timestamps: true
};

export const jsonSchema = {
    applicationId: {
        type: String,
        hashKey: true
    },
    name: String,
    description: String,
    scopes: [String]
};

export const Schema = dynamoose.Schema(jsonSchema, options);
export const Model = dynamoose.model("Application", Schema);
```

My service getting called
```
import * as Application from '../models/Application';
export async function createApplication(applicationData) {
    // console.log('table req ', Application.Model.getTableReq());
    let app = new Application.Model(applicationData);
    console.log('application data before saving ', app);
    app.save()
        .then(function(newApp) {
            console.log('saved application ', newApp);
            return newApp;
        }, function(err) {
            console.log('error saving to dynamo ', err)
        });
}
```

I have a ton of debug statements as I turned on DEBUG=dynamoose:*, let me know what is most helpful.

**Comment by fishcharlie** [comment]
@warnero I'm confused about what the problem is. Is the problem that the model creation is failing, or is the problem that `getTableReq` isn't working? When using DynamoDB Local and the model is set to be created it will create the table in your DynamoDB Local environment. You shouldn't need to use the `getTableReq`. It should handle it all for you.

**Comment by warnero** [comment]
Both? First it's that it just spins and won't actually create a table and second I can't create it myself because `getTableReq` doesn't exist anymore as a method for me to get the full table definition.

**Comment by warnero** [comment]
Gah! I see where my problem is! I'm recently switching over from Mongoose to Dynamoose and their Schema creation does not use the `new` keyword. Your Model creation also doesn't use the `new` keyword. I just copied over my code from a similar Mongoose schema and never checked to make sure that the Schema creation happened.

Mongoose
`export const Schema = mongoose.Schema(jsonSchema);`
`export const Model = mongoose.model("Account", Schema);`

Dynamoose
`export const Schema = new mongoose.Schema(jsonSchema);`
`export const Model = mongoose.model("Account", Schema);`

Now it's all good!

**Comment by fishcharlie** [comment]
@warnero Glad you figured it out!!!
