### ISSUE TITLE
ENV_VAR conflict with AWS Lambda reserved keywords

### ISSUE THREAD

**Issue by zhenyulin** [dynamoosejs/dynamoose#387]
when using dynamoose with serverless, if AWS_REGION not set in the env_var, dynamoose would throw error of region validation failure; if it is set via env var naming AWS_REGION, it would conflict AWS lambda in deployment.

Is there a better way than the workaround of setting the ENV_VAR with a different name and config dynamoose in code?

**Comment by fishcharlie** [comment]
You can use the `dynamoose.AWS.config.update` method to update the region and other AWS config settings. You can find an example of that method [in the documentation here](https://dynamoosejs.com/api#dynamooseaws).

**Comment by zhenyulin** [comment]
seems to be related to https://github.com/dynamoosejs/dynamoose/issues/251

`aws-sdk` is still expecting AWS_REGION when setup Dynamodb locally

**Comment by fishcharlie** [comment]
@zhenyulin Yep exactly! 😃
