### ISSUE TITLE
Model.update ADD only works for Number type

### ISSUE THREAD

**Issue by duxing** [dynamoosejs/dynamoose#388]
this is a weird issue and I was able to reproduce this with the example code.

```
var Schema = dynamoose.Schema;

var dogSchema = new Schema({
  ownerId: {
    type: Number,
    hashKey: true
  },
  name: {
    type: String,
    hashKey: true,
    index: true
  },
  breed: {
     type: String,
     enum: ['Golden retriever', 'Beagle']
  }
});

var Dog = dynamoose.model('Dog', dogSchema);
```

we'll create one record in the table with the following code:
```
var odie = new Dog({
  ownerId: 4,
  name: 'Odie',
  breed: 'Beagle'
});

odie.save(function (err) {
  if(err) { return console.log(err); }
  console.log('Ta-da!');
});
```

i've confirmed on my aws console this record exists without `age` column

now step 2. try updating the record and the schema.
 - update schema:
```
age: {
  type: String
}
```
 - update the record:
```
Dog.update({ownerId: 4, name: 'Odie'}, {$ADD: {age: '5'}}, function (err0) {
    if(err0) { return console.log(err0); }
    console.log('updated');
  })
```

then this error message surfaced:
> [ValidationException: Invalid UpdateExpression: Incorrect operand type for operator or function; operator: ADD, operand type: STRING]

weird thing is, if I change the type from `String` to `Number` and change value from `'5'` to `5`, this call goes through without any issue.

schema update seems mandatory to me since I tested without updating the schema and the data is not surfaced in AWS. if I enable `saveUnknown` then I get another different error message.

Please ignore the part where `String` is used as the type of `age`: I first ran into this issue on another project and tried reproducing it with the example from dynamoose and discovered this type related error message. 

Last but not least, envs:
 - dynamoose version: "~0.8.7"
 - node version: 0.12
I was running this sample app in a docker container built based on  `mhart/alpine-node:0.12` if it helps

**Comment by fishcharlie** [comment]
@duxing A PR to update that documentation would be very appreciated.

What do you want to happen if the attribute already exists?

**Comment by fishcharlie** [comment]
@duxing This is a DynamoDB level thing. Dynamoose passes those options directly to DynamoDB. So we don't really control the behavior of that code. You can submit a PR to fix this otherwise we'll get around to it when we can.

**Comment by duxing** [comment]
@fishcharlie I see. seems like dynamoose is simply passing the actions to aws cli:
https://docs.aws.amazon.com/cli/latest/reference/dynamodb/update-item.html

you're right. the dynamoose documentation is a bit misleading.

**Comment by john-aws** [comment]
@duxing Minor clarification: Dynamoose isn't "passing the actions to aws cli". It uses the [DynamoDB client](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-dynamodb/index.html) from the AWS JavaScript SDK.
