### ISSUE TITLE
Is there a way to specify projection for populate?

### ISSUE THREAD

**Issue by duxing** [dynamoosejs/dynamoose#389]
```
Dog.get(3).then(function(dog) {
  return dog.populate({
    dog.populate({
      path: 'parent',
      model: 'Dog'
    })
  })
});
```

`populate` call seems to fetch in every attributes in the target schema. is there away to set a projection?

e.g. 
```
dog.populate({
  path: 'parent',
  model: 'Dog',
  project: {
    name : true
  }
})
```

**Comment by duxing** [comment]
looked at the source code and it doesn't seems like it's supported.

**Comment by fishcharlie** [comment]
@duxing I haven't gone through the `populate` code very much. A PR for this would be awesome. 😃
