### ISSUE TITLE
dynamoose.local() not being recognized

### ISSUE THREAD

**Issue by warnero** [dynamoosejs/dynamoose#391]
I'm not sure what I did, but at one point in my functional tests I had this working properly. Then I moved on to working on a script to connect to the db and generate some records for me and I noticed that even though it said there were records I couldn't even find a table. So I checked my AWS and sure enough everything from my functional tests and the new script are being pushed there instead of locally.

I'll work off of my script as they're similar enough. Here's my debug output for top-level stuff.
``` 
./scripts-dist/scripts/CreateInternalApiToken.js  create -m auth -s 'auth,user'
  dynamoose Looking up model Application +0ms
  dynamoose Getting default DynamoDB +2ms
  dynamoose Looking up model AppToken +41ms
using local database
  dynamoose Setting DynamoDB to local (http://localhost:8000)
```
So it is actually setting up my dynamoose to point at local, but from what I've read this should be happening before the models are loaded? And I'm not even sure how that's happening. Here's my import section.
```
#!/usr/bin/env DEBUG=dynamoose node

const program = require('commander');
const dynamoose = require('dynamoose');

import config from '../config/settings';
dynamoose.setDefaults(config.get('dynamoose.defaultTableSettings'));
const awsConfig = config.get('dynamoose.awsConfig');
if(awsConfig !== null) {
    dynamoose.AWS.config.update(awsConfig);
}

const dynamooseLocal = config.get('dynamoose.local');
if (dynamooseLocal === true) {
    console.log('using local database');
    dynamoose.local();
}
import * as Application from '../services/Application';
```
The `Application` service is the only one that imports any model definitions and that *should* be happening after the dynamo config?

Any help resolving this is greatly appreciated. It would also be good to figure out how to enforce a db connection properly across the board whenever someone sets this because it seems to have bitten more than one person.

**Comment by fishcharlie** [comment]
@warnero What happens if you run a `console.log` inside of that Application service (where you input models)?  Or add a `console.log` inside each of your model files?

My question is, is for some reason the models being loaded before the `using local database` console.log? I haven't used the ES6 import syntax very much, so I'm not sure if there are behaviors that cause it to act differently than a `require`.

**Comment by warnero** [comment]
Output
```
loading Application model
  dynamoose Looking up model Application +0ms
  dynamoose Getting default DynamoDB +1ms
loading AppToken model
  dynamoose Looking up model AppToken +36ms
using local database
  dynamoose Setting DynamoDB to local (http://localhost:8000) +31ms
```
So the model class is getting pulled before my dynamoose.local is getting called.
```
const uuidv4 = require('uuid/v4');

import dynamoose from 'dynamoose'

console.log('loading Application model');
let options = {
    useDocumentTypes: true,
    useNativeBooleans: true,
    timestamps: true
};

export const jsonSchema = {
    applicationId: {
        type: String,
        hashKey: true,
        default: function() {
            return uuidv4();
        }
    },
    name: String,
    description: String,
    scopes: [String]
};

export const Schema = new dynamoose.Schema(jsonSchema, options);
export const Model = dynamoose.model("Application", Schema);
```

**Comment by fishcharlie** [comment]
@warnero That is the problem then. Either you are including/requiring that model somewhere else, or for some reason the include ES6 syntax gets hoisted to the top of the file.

**Comment by warnero** [comment]
And now I think I see why. I'm using babel to transpile and it is setting Application before my db local call happens.
```
var _settings = require('../config/settings');

var _settings2 = _interopRequireDefault(_settings);

var _Application = require('../services/Application');

var Application = _interopRequireWildcard(_Application);

function _interopRequireWildcard(obj) { if (obj && obj.__esModule) { return obj; } else { var newObj = {}; if (obj != null) { for (var key in obj) { if (Object.prototype.hasOwnProperty.call(obj, key)) newObj[key] = obj[key]; } } newObj.default = obj; return newObj; } }

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
const program = require('commander');
const dynamoose = require('dynamoose');

setupDb();
```

**Comment by fishcharlie** [comment]
@warnero The problem with that is Dynamoose has certain functions that get called on model load and throughout the lifecycle of the application that require it to be setup correctly. For example Dynamoose can create the table automatically. It also polls for when the table is actually active and ready to go before running any commands on it.

I think it would require a complete restructuring of how those systems operate, and setting it to `.local()` would require a lot of double check work to ensure the tables are setup correctly and all of that. It's not as easy as just changing the connection due to how much setup work goes into those tables.

**Comment by warnero** [comment]
OK, will dig into the babel side of things to see how I can get it to force load other stuff beforehand. Just noticed none of my default config is being loaded before either so that's messing with my prefix stuff.
