### ISSUE TITLE
does dynamoose  populate works when query returns more than one document?

### ISSUE THREAD

**Issue by venkataprasadmanne** [dynamoosejs/dynamoose#393]
i have to populate multiple  dynamoose documents using hashKey and rangeKey but its not working.
in the documentation, its mentioned that populate feature exists but they mention an example where they populate only one document,so i have modified that example to suit my needs. .I want both kittens to be populated with their owners phone number when i run this code but it throws error like **kittens.populate** method doesnt exist.

currently i need to achieve similar functionality in the project I am working on but I am not sure how to proceed ?is there any alternate solution if this cant be possible in dynamoose?

```
const Kitten = dynamoose.model('Kitten',
  {
    id: {
      type:  Number
    },
    name: {
      type: String
    },
    owner: {
      name: String,
      address: String
    }
  }
);

const Owner = dynamoose.model('Owner',
  {
    name: {
      type: String,
      hashKey: true
    },
    address: {
      type: String,
      rangeKey: true
    },
    phoneNumber: String
  }
);

var owner = new Owner({
  name: 'Owner',
  address: '123 A Street',
  phoneNumber: '2345551212'
});

var kitten1 = new Kitten({
  id: 100,
  name: 'Owned',
  owner: {
    name:owner.name,
    address: owner.address
  }
});
var kitten2 = new Kitten({
  id: 200,
  name: 'Owned',
  owner: {
    name:owner.name,
    address: owner.address
  }
});

kitten1.save();
kitten2.save();



Kitten.scan()
.exec(function(err,kittens) {
return kittens.populate({
   path: 'owner',
  model: 'Owner'})
  }).then(function(populatedKittens){console.log("populated cats are");console.log(populatedCats)})
```

**Comment by fishcharlie** [comment]
@venkataprasadmanne I haven't dived enough into the codebase for populate to comment much on this. But I **believe** a quick band-aid type fix would be to just map through the array and populate each one. Keep in mind I haven't tried this to see if it'll work, but that is the route I would go down to try to fix it.

```
Kitten.scan()
.exec(function(err,kittens) {
    return Promise.all(kitten => kitten.populate({
        path: 'owner',
        model: 'Owner'
    }))
}).then(function(populatedKittens){console.log("populated cats are");console.log(populatedCats)})
```

Let me know how it goes!

**Comment by venkataprasadmanne** [comment]
@fishcharlie I will try that.
One more concern I have is to populate array of refs like populating all kittens  of owner if owner item holds arrays of  objects containing kitten Id and name and we need to populate all attributes of kittens belonging to owner.I thought of manually doing this  but running into lots of asynchronous issues .

**Comment by fishcharlie** [comment]
@venkataprasadmanne I don't totally understand what you mean. Can you share an example or something of what you are concerned about?

**Comment by venkataprasadmanne** [comment]
@fishcharlie sorry, i should have mentioned code.I want to achieve functionality similar to below

```
const Kitten = dynamoose.model('Kitten',
  {
    id: {
      type:  Number,hashkey:true
    },
    name: {
      type: String,rangeKey:true
    },
    age: Number,
	
	colour:String
  }
);

const Owner = dynamoose.model('Owner',
  {
    name: {
      type: String,
      hashKey: true
    },
    address: {
      type: String
    },
    phoneNumber: String,
	
	pets:[{id:Number,name:String}]
  }
);

var owner = new Owner({
  name: 'Owner',
  address: '123 A Street',
  phoneNumber: '2345551212'
  pets:[{id:100,name:"white kitten"},{id:200,name:"black kitten"}]
});

var kitten1 = new Kitten({
  id: 100,
  name: 'white kitten',
  age:5,
  colour:"white"
});
var kitten2 = new Kitten({
  id: 200,
  name: 'black kitten',
  age: 6,
  colour:"black"
});

owner.save()
kitten1.save();
kitten2.save();





Owner.scan()
.exec(function(err,owner) {
return owner.populate({
   path: 'pets',
  model: 'Kitten'})
  }).then(function(populatedOwner){console.log(populatedOwner)})
  
  
  
  //output should be 
  
 { 
  name: 'Owner',
  address: '123 A Street',
  phoneNumber: '2345551212'
  pets:[
  {
  id: 100,
  name: 'white kitten',
  age:5,
  colour:"white"
  },
  {
  id: 200,
  name: 'black kitten',
  owner: 6,
  colour:"black"
  }]
  }
```
Thanks in advance

**Comment by fishcharlie** [comment]
@venkataprasadmanne I would suggest trying the syntax before reporting bugs. Without exact details about an error message you are receiving there isn't much we can do. If you still run into issues please submit a PR adding a broken test to the test suite to replicate the issue you are having, then please link the PR to this issue.

In the meantime I would suggest looking into some of the JavaScript promise features. Notably `async`/`await` as well as `Promise.all`. Some of these features might help with the type of work you are wanting to do. But I'm still having trouble understanding what exactly the problem is.

Good luck!

**Comment by fishcharlie** [comment]
@venkataprasadmanne Awesome! Glad it hear it worked for you!!
