### ISSUE TITLE
Getting Model class object inside a Schema method

### ISSUE THREAD

**Issue by dolsem** [dynamoosejs/dynamoose#397]
In Mongoose you can get a model class object inside a schema method by calling `this.model(modelName)`, as you can see [here](http://mongoosejs.com/docs/guide.html#methods). Is that implemented in Dynamoose? If not, I'll submit a PR.

**Comment by fishcharlie** [comment]
@dolsem I'm not aware of this being a feature. I would first test it by writing a test case. If it works, we should probably edit the documentation to reflect that. If it does not work, we should implement it, and add it to the documentation as well.

So either way at minimum writing a test case for it and updating the documentation. If it isn't supported, adding support as well.

A PR would be amazing!
