### ISSUE TITLE
How to sort all items according to registration date.

### ISSUE THREAD

**Issue by sabreenakp** [dynamoosejs/dynamoose#436]
### Summary:
How to sort all items according to registration date. When I tried it gives me no output, My code is shown below

### Code sample:

abcdschema.statics.fetchall = function fetchall(cb) {
var id_temp='abcd';
this.query('id').contains(id_temp).where('regDate').ascending(function(err,res){
        console.log(err,res);
    })
}

#### Schema
   id: {
        type: String,
        required: true,
        hashKey: true
    },
    name: {
        type: String,
        required: true,
        rangeKey: true
    },
    regDate: { type: Date, required: true, default: Date.now },
    activeFlag: { type: Boolean, default: true }

### Current output and behavior:
Not working, giving no output

### Expected output and behavior:
all items in which id contains id_temp  and will be sorted according to regDate

### Environment:

Operating System: ubuntu
Operating System Version:14.04
Node.js version (`node -v`):9.3.0
NPM version: (`npm -v`):5.5.1
Dynamoose version:0.8.7

### Type (select 1):
- [ ] Bug report
- [ ] Feature suggestion
- [ 1] Question
- [ ] Other suggestion
- [ ] Something not listed here

**Comment by fishcharlie** [comment]
@sabreenakp Pretty sure you need to say what `id` is equal to. You can't query where something contains. I'm like 99% sure this code should produce an error. Can you please post the error that Dynamoose is returning?

**Comment by fishcharlie** [comment]
You also aren't using the [`Query.exec()`](https://dynamoosejs.com/api#queryexeccallback) function. Therefor your query will never be run.

Closing this issue now, if you are still having problems feel free to comment and I can try to help further.

**Comment by sabreenakp** [comment]
@fishcharlie  Thanks for the reply

Now when I tried I got an error, eq must follow query, one issue with my table is there is a chance of the same hash key and range key come more than once, so I am making it unique by appending with the date of creation, that is why I couldn't use eq.

Is there any good way of making your schema when there is a chance of same hash key and Range key?

I am pasting the error i got 


{ QueryError: Invalid Query state: eq must follow query()
    at Query.compVal (/home/sabreena/sparton/mca_service/node_modules/dynamoose/lib/Query.js:357:30)
    at Query.contains (/home/sabreena/sparton/mca_service/node_modules/dynamoose/lib/Query.js:453:17)
    at Function.fetchDeviceRecordings (/home/sabreena/sparton/mca_service/api/recording/recording-schema.js:92:26)
    at Object.fetchDeviceRecordings (/home/sabreena/sparton/mca_service/api/recording/recording-service.js:26:20)
    at fetchDeviceRecordings (/home/sabreena/sparton/mca_service/api/recording/recording-controller.js:10:20)
    at Layer.handle [as handle_request] (/home/sabreena/sparton/mca_service/node_modules/express/lib/router/layer.j
s:95:5)
    at next (/home/sabreena/sparton/mca_service/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/sabreena/sparton/mca_service/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sabreena/sparton/mca_service/node_modules/express/lib/router/layer.j
s:95:5)
    at /home/sabreena/sparton/mca_service/node_modules/express/lib/router/index.js:277:22
  name: 'QueryError',
  message: 'Invalid Query state: eq must follow query()' }

**Comment by sabreenakp** [comment]
Now I am trying to do just like below, but still, the response is not sorted according to the date.

`this.query({ 'id': id_temp, activeFlag: true }).where('regDate').descending().exec(function (err, res) {
        if (err) {
            cb(err);
        } else {
           cb(null,res);
        }
})`

here regDate is type Date.

**Comment by fishcharlie** [comment]
@sabreenakp You need to set the range key on your index. Take at look at the following code in the test files for how to do a descending query.

https://github.com/dynamoosejs/dynamoose/blob/5be0d182e3a6ead82bda7c471ce4c431f24209d7/test/Query.js#L47
https://github.com/dynamoosejs/dynamoose/blob/5be0d182e3a6ead82bda7c471ce4c431f24209d7/test/Query.js#L267
