### ISSUE TITLE
Community Feature Feedback

### ISSUE THREAD

**Issue by fishcharlie** [dynamoosejs/dynamoose#467]
I would love to get some input from the community about what things you believe are most important for the future for Dynamoose. I have listed some ideas below about potential future goals for Dynamoose.

I would love to get some feedback about which of the items below you'd like to see most, and if you have any other ideas you'd like to see from this package I'd love to hear those too (even more so than my ideas).

Please keep in mind, that these are just ideas and meant to determine interest. I do not guarantee that these will get done, and as always, the most support on these tasks from the community, the quicker they will get achieved, and the better this package will be.

---

### Community

- Dynamoose Twitter Account (for updates, and to answer questions from the community)
- Develop Node.js version support policy (which versions of Node.js we will support, and for how long)
- Better support (more active) for the Gitter channel
- Create a CONTRIBUTING.md file
- Create a Code of Conduct
- More examples on https://dynamoosejs.com/examples
- Rewrite documentation from the ground up
- Redesign website
- More transparency about what it takes to become a member of this GitHub org

### General

- More automated testing (set a goal of 100% code coverage)
- More ES6 refactoring
  - [Classes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes)
  - [`async`/`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) (I know this isn't ES6, but still putting it in this category, keep in mind this would be internally only, you can use `async`/`await` in your applications with Dynamoose today)
  - Update documentation to ES6
  - Update tests to ES6
- More issue templates (ex. https://github.com/fastlane/fastlane/issues/new/choose)
- `Model.find` support

**Comment by shauntck** [comment]
would be neat to see how you would deal with migrations and continuous integration within an app using dynamoose

**Comment by fishcharlie** [comment]
@shauntck Can you give some detailed examples of what you mean?

**Comment by shauntck** [comment]
I think in general how you use dynamoosejs to evolve your schema over time (think multiple environments in different states at different times, and/or using continuous integration/deployment).

What do you do when you need to add additional attributes, tables, indexes, etc. Most ORMs i've seen have this functionality or at least leverage a library to manage this sort of thing. Here's an example - https://sequelize.readthedocs.io/en/v3/docs/migrations/

**Comment by fishcharlie** [comment]
@shauntck The concept of migrations doesn't apply to DynamoDB or NoSQL databases. The whole reason you need migrations in SQL based databases is because it is a truly strict database at the core. You aren't allowed to store an attribute if it doesn't exist in the table schema in SQL based databases. Whereas in DynamoDB you can store whatever you want. Dynamoose of course adds more of a schema around your data, but DynamoDB itself you can store whatever you want, no need to create attributes on DynamoDB.

For attributes, you just add them to your Dynamoose schema.

For tables, you just create a new Dynamoose schema, and it'll be created automatically for you if `create` is set to true (which it is by default).

For indexes, you can just add it to your Dynamoose schema, and it'll be created for you automatically if `update` is set to true.

---

Hopefully that helps clear up the confusion. Just differences between SQL and NoSQL at the end of the day.

**Comment by shauntck** [comment]
I definitely am new to dynamo to some degree so apologies if i'm not making a lot of sense. i understand what you mean regarding the core schema as far as a traditional rdb (the tables and columns) is different from dynamo in that you don't have to declare the columns first ... but migrations is more than just schema changes, it's also how you migrate the data into a new format ( even if it's a loosely defined schema).
I get that this may be outside of the scope of dynamoose. I may be looking for something baked into dynamoose (as it's typically with an orm) but i think could use something like umzug *(https://github.com/sequelize/umzug) which just has a loose framework for managing forward/backward of running scripts and current state.
current state

**Comment by shauntck** [comment]
i see what you are saying... by just setting the dynamoose schema it will automatically make those updates. 

still seems like there's some kind of scripts you would have to build up / execute from time to time to migrate if your internal schema is changing but i guess that doesn't dynamoose doesn't have to solve that problem necessarily.

**Comment by fishcharlie** [comment]
@shauntck I'm still not following. Without more detail I can't really help. Can you provide an example of what you mean? Part of this is just fundamental database design.

Like of course, if you add a new attribute to your schema, that you want to have a default for all your existing records, then yeah, you would probably have to write a script that goes through and adds that default value to all your existing items.

Or if you want to rename an attribute to your schema then you would have to go through and update all existing records.

But if you just wanna add an attribute for future use, just add it to your schema and use it.

---

I haven't given it a lot of thought at all, but I'm not so sure Dynamoose should handle those more complicated migrations. In Sequelize, I'm pretty sure it just executes standard commands on the database and doesn't actually touch the data at all. In Dynamoose there would be no way to do this without touching your data. Which I'm pretty firmly against. I don't believe Dynamoose should be responsible for editing, deleting, creating, etc. your data. It's really meant to be a wrapper around the DynamoDB API and add modeling features. Of course the major exception to the `don't touch your data` rule is the timestamp feature. So there are exceptions.

I'm not even sure I would consider Dynamoose an ORM. But I've heard those terms be misused so often, that I'm not totally gonna correct anyone who calls it an ORM. It's just important to understand what Dynamoose is meant for.

---

Now of course, if you want to run those more complicated migrations, you can use Dynamoose to help you with that.

---

That all being said, I have considered building a Dynamoose CLI before. That helps create models and schemas, and might be perfect for some of those more complicated migrations. But we have a long way to go before that ever happens. There is not even an issue for that yet. And it's not even really on my radar. SOOO many things that need to be done in this project before we even consider a Dynamoose CLI.

**Comment by zaun** [comment]
The only time a "migrate" would have to happen is changing indexes. You'd have to create a new table, copy all the data over, remove the old table.

That said, we just create the new table, and copy the data over. We don't remove the old table. To do this we just create a new schema and have a bit of code to copt things over. The old schema stays around if we ever need access to the old data.

**Comment by shauntck** [comment]
Thanks for the clarification @fishcharlie . Your examples of adding a default is sufficient to make my point. I wouldn't expect you to automatically fix that but possibly providing a framework where the scripts could be run forward or backward within a continuous deployment pipeline was what I was thinking. This is very common in most orms I have seen. I understand though that dynamoose isn't really including this as part of what it does and that's makes sense.

I think I'm looking for something like this ...  https://github.com/sequelize/umzug

**Comment by fishcharlie** [comment]
@shauntck PRs are always welcome.

**Comment by shauntck** [comment]
I'll give it some thought. I appreciate your help in thinking through this with me. The library looks really cool and helpful. Good job!

**Comment by dolsem** [comment]
Any plans for adding usage with TypeScript to documentation?

**Comment by blakedietz** [comment]
Any plans to overhaul the documentation? It feels pretty difficult to use from my experience. Speaking of which I would love to help with this front.

**Comment by blakedietz** [comment]
Any plans to add more core maintainers? It seems like @fishcharlie could use some help fielding more issues.

**Comment by fishcharlie** [comment]
> Any plans for adding usage with TypeScript to documentation?

@dolsem No plans as of right now.

**Comment by fishcharlie** [comment]
> Any plans to overhaul the documentation? It feels pretty difficult to use from my experience. Speaking of which I would love to help with this front.

@blakedietz Documentation has always been the biggest struggle for this project. I'm **slightly** considering rewriting Dynamoose from scratch for v2.0 as part of #671. If I do that documentation will be a high priority for that rewrite. That being said, I'll need to find some major time to really dive into that project, and will need some organizational things to be in place before that can start.

> Any plans to add more core maintainers? It seems like @fishcharlie could use some help fielding more issues.

Hopefully at some point 😄. I go through phases where I'm more and less active on the project. I use it in a lot of my personal projects but recently it's been more difficult to maintain due to outside things in my life. I still truly believe in the project and don't want to see it die. So it's still considered active and have no plans to deprecate it anytime soon. It is also mostly in a working state, and is used in my small apps in production.

If anyone is interested in becoming a maintainer the process currently is to show a strong level of commitment to the project through PRs and being active for a extended period of time, then get in touch with me and we'll make it happen! There just hasn't really been anyone who has expressed interest who has been involved extensively for a long period of time.
