### ISSUE TITLE
Missing lastKey for scan filter expresion

### ISSUE THREAD

**Issue by vincentkwok** [dynamoosejs/dynamoose#474]
### Summary:

`scan()` with filter expression returns found models [code](https://github.com/dynamoosejs/dynamoose/blob/master/lib/Scan.js#L92) without last key. 

It cannot fit for case with data exceed 1MB (scan limit), and to have more rounds of scan then.

**Comment by fishcharlie** [comment]
PR open at #475. @vincentkwok, wanna review that and let me know if it fixes your issue and give any feedback you might have?
