### ISSUE TITLE
Redesigning new website

### ISSUE THREAD

**Issue by rish-16** [dynamoosejs/dynamoose#494]
Hello,

I am currently redesigning and redeveloping the dynamoose website as stated in ROADMAP.md
<img width="1280" alt="screenshot 2018-12-05 at 6 24 43 pm" src="https://user-images.githubusercontent.com/20137995/49507286-2057d500-f8bb-11e8-9c47-9133b863dcb6.png">

Any inputs are welcome :)

Cheers,
Rishabh

**Comment by fishcharlie** [comment]
@rish-16 ❤️ the design!!

Just replied at the link below.

https://github.com/dynamoosejs/dynamoose/pull/496#issuecomment-444517943
