### ISSUE TITLE
Dynamoose connection to AWS dynamoDB is https or http?

### ISSUE THREAD

**Issue by sabreenakp** [dynamoosejs/dynamoose#498]
### Summary:
I am using dynamoose with Node.js to connect to Amazon DynamoDB. I come across some detail finding of security around the connection establishment. Could you please give details on the same?

How does the connection work?
Is it HTTP or HTTPS?  

### Code sample:

dynamoose.AWS.config.update({
  region: config.aws.region
});

Dynamoose version:

0.8.7

**Comment by fishcharlie** [comment]
@sabreenakp This is not a Dynamoose question. Dynamoose just uses the underlying AWS-SDK, and doesn't handle connections at all.
