### ISSUE TITLE
ON_DEMAND breaks table creation with global secondary index

### ISSUE THREAD

**Issue by batmanppc** [dynamoosejs/dynamoose#503]
### Summary:

Create table fails if throughput set to ON_DEMAND and table includes a global secondary index.

### Current output and behavior:

MultipleValidationErrors: There were 2 validation errors:
* MissingRequiredParameter: Missing required key 'ReadCapacityUnits' in params.GlobalSecondaryIndexes[0].ProvisionedThroughput
* MissingRequiredParameter: Missing required key 'WriteCapacityUnits' in params.GlobalSecondaryIndexes[0].ProvisionedThroughput

**Comment by fishcharlie** [comment]
@batmanppc Do you mind sharing a concrete example of this? Or even better creating a failing test case for this and submitting a PR? Or the best option, do you wanna try to fix this and submit a PR? Haha.

**Comment by batmanppc** [comment]
@fishcharlie Yes, absolutely have plans to. Just wanted to get the issue logged in case someone else ran into it.

**Comment by fishcharlie** [comment]
@batmanppc Awesome!! Thanks so much!

**Comment by michalkotowski1** [comment]
This is still an issue, check schema below
`referenceDocumentNumber: {
      type: String,
      index: {
        name: 'referenceDocumentNumber-index',
        global: true,
        throughput: 'ON_DEMAND', // do not work, err: ProvisionedThroughput is not specified for index: referenceDocumentNumber-index
        throughput: {"read": 5, "write": 10} // this works
      },
    },`
