### ISSUE TITLE
Populating an array of objects **help wanted**

### ISSUE THREAD

**Issue by BramSikkens** [dynamoosejs/dynamoose#507]
Hi! 

I have a question about populating. I saw that you updated the code to use populating like mongoose, but there is still no documentation.

I have the following schema

`
```
var PhysioSchema = new Schema({
    userid: {
        type: String,
        required: true,
        hashKey: true
    },
    username: {
        type: String,
        required: true
    },
  programs:[{
        program:
        {
            type: String,
            ref: 'Program'
        }
    }]
}, {
    useDocumentTypes: true
});
```

*programs* should be populated with a Program model. The schema for the program looks like this
```
var ProgramSchema = new Schema(
    {
       programid:{
            type: String,
            required:true,
            hashKey: true,
        },
        ownerid:
        {
            type: String,
            required:true
        },
        programtitle:
        {
            type : String,
            required: true
        },
        programdescription:
        {
            type:String
        },
        exercises:[
        {
            exerciseid: String
        }]
        
    }
);
```

So basicaly a physio should be stored like this  with *2 programs*
   ```
var newPhysio = new Physiotherapist({
        userid: "1",
        username: "Bram Sikkens",
        programs: [{program:'1'},{program:'2'}],
        exercises: [{
            exerciseid: "1"
        }],
        libraries: [{
            libraryid: "1"
        }],
        patients: []
    });
```

The json response looks like this 

```
Model-Physiotherapist {
  programs: [ { program: '1' }, { program: '1' } ],
  exercises: [ { exerciseid: '1' } ],
  username: 'Bram Sikkens',
  patients: [],
  libraries: [ { libraryid: '1' } ],
  userid: '1' }
```

How do I populate programs array with the Program model? 
I already tried
```
    physio.populate({
            path:'programs.program',
            model:'Program'
        }).then(function(populatedphysio){
            console.log(populatedphysio);
        })
```
But this does not work

**Comment by fishcharlie** [comment]
@BramSikkens Few things before I get to your question. First, adding `**help wanted**` to your title doesn't really serve any purpose and takes away from the focus of your question that you are really asking. At the end of the day if you file an issue on GitHub, chances are you are looking for help, support, or at the very least a reply. So in the future, please try to keep your issues focused and on topic. I promise I will make every effort to answer issues as quickly as possible 😃. Adding `**help wanted**` doesn't change that fact, and if anything delays the time it takes for me to reply to your issue.

Second, we have an issue template on GitHub that gives us a lot of useful information to help solve your issue quicker. There are very few reasons not to follow the issue template. In your issue you say `But this does not work`. That doesn't give me enough information **at all** to help solve your issue. How doesn't it work? What is the current output? Is it giving you an error? Is it failing silently? Those are all questions that the issue template helps to encourage you to write in your issue. So in the future, please follow the issue template. 

---

On to your issue.

Short answer, I don't think this is currently possible with the populate feature. I could be totally wrong, but I don't think it's currently possible. Although I haven't really used populate in one of my projects before, so I really am not really sure the complete scope of this feature.

My suggestion would be to do something like the following:

```js

async function getAndPopulate() {
  const myItem = await Physiotherapist.get("1");

  myItem.programs = await Promise.all(myItem.programs.map(async program => {
    const myProgram = await Program.get(program.program);
    return myProgram;
  }));

  return myItem;
}

```

If my code is correct, that should loop through the programs array, and get each program item for the program id in the array.

Of course you probably want to add in some `try`/`catch` statements to handle errors, and might want to edit the code to fit your needs better. But the overall concept and underlying ideas should work.

---

If you would like to go and do some investigating into the Dynamoose codebase to check to see if this is supported natively that would be awesome too. If it's not supported, feel free to submit a PR adding support for it.

Either way, probably should add some documentation for this (again, PR would be great).

---

Hopefully this helps! Feel free to comment if you have further questions.

**Comment by BramSikkens** [comment]
First of all, thank you for the reply. I fairly new to the whole issue thing so, I didn't really know how I it was the proper way to ask a question. I added the help wanted to clarify that it was not an issue, but a question. It was not my intention to push for your attention.

I was reading an issue about the implementation of the populate method, like mongoose. The only thing missing was the documentation. I am just starting with dynamoose and when I understand it fully I will try to add some help to your incredible tool. 

Just thanks for the help!

**Comment by fishcharlie** [comment]
@BramSikkens Totally understand!

Hopefully that works and feel free to create more issues as you have more questions, bug reports, suggestions, etc. And as always PRs are always welcome! haha

Good luck!
