### ISSUE TITLE
Recommended method for creating tables

### ISSUE THREAD

**Issue by glenarama** [dynamoosejs/dynamoose#513]
What is the recommended method for Table creation?

The Docs recommend that create be disabled for production environments, and relying on a query to create the table causes a timeout for the query. 

The new option for On demand billing simplifies table config a lot - I was trying to find a table.check and table.create based on the model (With prefix name) but cannot find such a method.

**Comment by fishcharlie** [comment]
For production I would just create the table manually before deployment.
