### ISSUE TITLE
Fetching data with specific items in array

### ISSUE THREAD

**Issue by BramSikkens** [dynamoosejs/dynamoose#526]
### Summary:
Hi Is it possible to fetch all data that contain a specific item in an array attribute? I give you an example
```
User{
           dogs:[{
                 dog: {
                       dogid:1
                       dogname:blacky
                       }
                 dog: {
                       dogid:2
                       dogname:doggie
                       }]
}      
      
```

Is it possible to get all the users whom have a dog called blacky. I know indexes ar not possible because this only works with non child attributes. It would be awesome to use a query, but I think it needs some kind of scan?

I would need it because when a dog is updated I need every user and update the single dog item that is changed.

Thanx!

**Comment by fishcharlie** [comment]
I don't think this is possible with DynamoDB, and therefor not possible with Dynamoose.
