### ISSUE TITLE
Getting unexpected results array when using FilterExpression with scan

### ISSUE THREAD

**Issue by manuelxaguilar** [dynamoosejs/dynamoose#550]
### Summary:

I'm trying to get some items returned if the value of one of their attributes is contained within an array of values that I'm passing over.

#### General
```
issues = await Model.scan({
  FilterExpression: 'contains(:ids, itemId)',
  ExpressionAttributeValues: { ':ids': params.ids } // params.ids looks like ['id1', 'id2', 'id3']
}).exec()
```

### Current output and behavior:

Within the results I'm getting the correct items back, however, what I'm getting is not an object that includes a property "Items" with those results, instead, I get an array for which when I use Object.keys over, it looks like this:

```
[ '0',
'1',
'2',
'3',
 '4',
'5',
'6',
'7',
'8',
'lastKey',
 'count',
'scannedCount' ]
```

Were the value to each of the "numeral" keys is an actual item (object) and then the last three are the "count" props you would expect.

This, of course, makes it hard to use the data (manipulate it somehow, such as mapping over the items), because of those last three props.

### Expected output and behavior:

I would expect something similar to what you'd receive from a native DynamoDB result. Something that looks kind of like:

```
{'items': [...] // with this being a list of the results
'lastKey': 0, // or any number
 'count': 0, // or any number,
'scannedCount: 0, // or any number' }
```

I can see that this is happening here:

https://github.com/dynamoosejs/dynamoose/blob/155729cda824cb4136e5e0de1a070d9de87b98e8/lib/Scan.js#L85-L103

However,  I'm still wondering if I'm doing something wrong with the query or missing something here in order to get a hold of the data in a clearer way. 

Is this intended behaviour? Any suggestions for good practices on how to "properly" get those items back helps. Thanks a lot!

**Comment by fishcharlie** [comment]
@manuelxaguilar This is the expected behavior.

I have no idea why you are trying to do `Object.keys` on the result. That seems a little bit weird to me. Is there a reason you are doing that? Maybe there is a work around to get the result you want.

Overall we are just adding properties to the array we return. It's still an array you can work with. All the Array prototype methods and properties are available, so you can treat it like a normal array. And those extra properties shouldn't effect your ability to use those standard methods and properties.

These extra properties should in no way hinder your experience, it should only help you get relevant data about the scan or query (should you need it).

**Comment by manuelxaguilar** [comment]
Well, sorry, I thought it was clear that I was running Object.keys to showcase the result's shape, I'm not actually using that on my code.

But that's why I asked if it was intended behaviour.

I did notice an aditional thing, if I don't use a raw filter (instead I just use a regular scan and then filter by that criteria using pure javascript over the results) I get the items back with the correct data types. For instance, I get this:

```
{
  created_at: 1548396987163,
  arrOne: [],
  count: 0,
  overview: 'Test 8',
  created_by: 'randomString',
  arrTwo: [],
  arrThree: [],
  arrFour: [],
  network: 'randomStringNtw',
  arrFive: [],
  active: true,
  otherProp: 'randomStringOther',
  last_updated_at: 1548396987163,
  description: 'Test 8 Desc',
  id: 'randomStringId' 
}
```

However, by using the FilterExpression above, I'm getting this (notice that the empty arrays are now strings) and that has broken different parts of the code since it's no longer iterable:

```
{
  created_at: 1548396987163,
  arrOne: '[]',
  count: 0,
  overview: 'Test 8',
  created_by: 'randomString',
  arrTwo: '[]',
  arrThree: '[]',
  arrFour: '[]',
  network: 'randomStringNtw',
  arrFive: '[]',
  active: true,
  otherProp: 'randomStringOther',
  last_updated_at: 1548396987163,
  description: 'Test 8 Desc',
  id: 'randomStringId' 
}
```

Is there a way to avoid that or to easily parse it into the correct value (an actual empty array and not a string).

Thanks.

**Comment by fishcharlie** [comment]
@manuelxaguilar Yeah those extra properties shouldn't effect anything tho.

That really sounds like a separate issue. And without more information I really can't answer it. What does your schema look like? What does your model look like? What version of Dynamoose are you running? etc.

Also I'm not sure if this is the issue, but your filter expression looks like it's not correct at all.

First of all I don't see `itemId` anywhere in your object's you posted.

Second this link (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html) shows that you put the path first and the operand second.

I would verify that your filter expression works as intended with DynamoDB directly.

One other tip, you can run `export DEBUG=dynamoose*` to get more information about what is happening behind the scenes about Dynamoose. That can help you debug things and see what is getting sent to DynamoDB, and what the responses look like.

Good luck!

**Comment by fishcharlie** [comment]
@manuelxaguilar Oh one more thing. If DynamoDB is storing it as a string, it's harder to do filters and such on it. So in that case, yes, it is probably easier to do it on your end. There is a lot of information in other issues (see #445 and #446). We also made a breaking change in version 1.0.0 that kinda changed this behavior.

That being said, you have to consider what that means. DynamoDB charges for every GB sent out to the internet (I believe it is). So the more data that gets returned to you, the more expensive it will be. Overall there are reasons you'd want to let DynamoDB handle it for you. But it really depends on a lot of factors that only you will know.

---

At some point I'd love to go and clean up the whole code related to maps vs objects and lists vs arrays. I personally don't see the difference between the two. Yet they are different in Dynamoose. It would be a major breaking change and a huge undertaking.

It would also require a massive update to the documentation. I'd also love to update the documentation to give more information about your original question.

That all being said, this is open source. And while I'd love to get around to those things, there is a limited amount of time I have to get stuff done on this project. Any help would be much appreciated! 😃

**Comment by manuelxaguilar** [comment]
@fishcharlie Yes, that's a separate issue for sure, just thought I'd ask since I'm not sure it's worth creating a new issue for it.

Well, `itemId`, as the other props on the object, are just mock names. I updated it to though just to be extra clear. And the schema looks pretty much like the object you're seeing, where the string arrays are actually arrays, the strings are just that, and so on.

It definitely is possible that I'm setting up the query in an incorrect manner, however I'm not sure that's the case, since, again, I'm running it with different parameters and modifying items and always getting the correct results, so I'm pretty sure that (somehow then?) I'm executing it correctly. Right now it's just a matter of that it's returning some of the props as strings (which as I mentioned, I believe is how it's getting stored on Dynamo), however, again, when I just run a simple scan without the FE I get those values as actual arrays, so I figured there was some clear processing going on behind the scenes to convert those values over the the inteded type declared on the schema.

But thanks for your time, I'll be sure to use the debug method.

**Comment by fishcharlie** [comment]
There is. If it’s an array or object and we store it as a string on DynamoDB we should be doing a JSON.parse before returning it back to you.

It very well could be a bug. If you want to try to create a self contained, complete, and simple reproducible example that I can play around with and debug I’d be happy to take a look further.

**Comment by manuelxaguilar** [comment]
@fishcharlie Sure, I'll try to make some time to create a reproducible example to share. I can tell you that with the following changes the problems **seems** to be solved:

https://github.com/manuelxaguilar/dynamoose/commit/decf8167ea1fb32af18dc42b5cd8c5fa76a27908

However the four tests in place for raw AWS filters are failing on this line:

https://github.com/dynamoosejs/dynamoose/blob/6654a5c576e0c9b1ed6348f3054019196408842e/lib/Attribute.js#L560

With a `(node:42427) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'map' of undefined` error, as `set` is _undefined_.

And that's because for the non-raw filtered tests, the items are returned like so:

```
{ name: { S: 'Foxy Lady' },
  ownerId: { N: '1' },
  color: { SS: [ 'black', 'brown', 'white' ] },
  breed: { S: 'Jack Russell Terrier' } }
```

Where as with raw AWS filters, the items are returned like this:

```
{ name: 'Snoopy',
  details: { timeWakeUp: '8am', timeSleep: '8pm' },
  ownerId: 19,
  color: [ 'black', 'white' ],
  cartoon: true,
  breed: 'Beagle' }
```

So the following evaluation fails for the `color` array:

https://github.com/dynamoosejs/dynamoose/blob/6654a5c576e0c9b1ed6348f3054019196408842e/lib/Attribute.js#L559

Interesting enough this didn't affect my app's results (the app is on a local environment, however it is connected to an AWS Dynamo instance, not a local one.

I'm aware that this probably doesn't tell you much but I'll try to work on a full example. If, on the meantime, you have any suggestions for the failing tests just off the top of your head, I can work on those too. Also, I'm clearly not too familiar with Dynamoose's codebase, so if this implementation is for some reason a no-go from the start, then I can try to come up with a different approach when I get some time.
