### ISSUE TITLE
How to use contains with or

### ISSUE THREAD

**Issue by amitava82** [dynamoosejs/dynamoose#592]
I'm trying use contains to filter by multiple values from a list.
```
# sample data
 {
            "owner": "u1",
            "products": [
                "foo",
                "bar",
                "one"
            ]
}
``` 
```
# Query
var params = {
  TableName : "test",
  KeyConditionExpression: "#u = :owner",
  FilterExpression: "contains (products, :p1) OR contains (products, :p2)",
  ExpressionAttributeNames:{
    "#u": "owner"
  },
  ExpressionAttributeValues: {
    ":owner": 'u1',
    ":p1": "one",
    ":p2": "bar",
  }
};
```
I've tried using contains query which seems to take single value. Is there a way to combine `or` and `contains` together for the desired result?

**Comment by fishcharlie** [comment]
@amitava82 Closing this issue since this is a general DynamoDB question, not Dynamoose specific.

**Comment by amitava82** [comment]
Not really a DynamoDB question since I've already provided the DynamoDB query that I want to achieve with your library.

**Comment by fishcharlie** [comment]
@amitava82 I think I totally misunderstood. That query you posted works in DynamoDB? But doesn't work in Dynamoose?

**Comment by amitava82** [comment]
Correct. That is the query I'm looking to do with the library. I was looking at the code and it seems `contains` only take single value or perhaps there is other way to do it.
