### ISSUE TITLE
Schema Migrations

### ISSUE THREAD

**Issue by dolsem** [dynamoosejs/dynamoose#609]
### Summary:
I think schema migrations (discussed in #467) should be part of Dynamoose. I'm referring to things like renaming fields or changing which fields should be hash and range keys. The reason is that Dynamoose is what manages schemas, as well as relationships between schemas and raw DynamoDB data. I think by supporting migrations Dynamoose can make this process significantly easier than it is right now. Migrations are usually not a question of why, but a question of when, so this problem is very relevant.

I might consider implementing this functionality very soon, but here's a disclaimer. I don't have experience maintaining databases and performing migrations, and I am not familiar with common practices. Any feedback and suggestions about my idea or any other help will be greatly appreciated.

I am thinking of a plugin (I'm not yet set on this, so I'm creating this issue here and not in plugin ideas for now). When you update your schema you move your old one to a separate file (perhaps inside migrations folder), and when you use the plugin you specify array of previous schemas as options.

Migration API is imperative - you provide a callback function in plugin options for each migration that takes an object with an old schema version and converts it to the new schema version. So imagine you have 4 versions of your schema. That means 3 migrations, so you provide 3 functions. If you then need to convert your table from version 1 to version 4 the plugin will create a new table and run all functions in sequence on every object to convert it to the most recent version and store in the new table. It will map schema versions to table names (based on a suffix or a prefix) and automatically select the table that corresponds to the right schema version.

The plugin can keep migrations information such as current schema version in a separate table. This way if you forget to perform a migration the plugin will detect that your defined schema has a higher version that the one currently present in the table and throw an error.

The plugin package can include a tool that can perform migrations from CLI. You would just specify path to the module where your schema is defined, and optionally to the file that contains Dynamoose initialization. It can then detect and perform all needed migrations and output the results. If you have ideas let me know what information exactly you want to see logged.

CC @shauntck

### Type (select 1):
- [ ] Bug report
- [x] Feature suggestion
- [ ] Question
- [ ] Other suggestion
- [ ] Something not listed here

**Comment by fishcharlie** [comment]
The one situation that I ran into recently, that I have no idea how to fix. Is if you have a table created, that you are using in production. How do you add or delete an index from that table?

If you just manually do it via the AWS Console or something before deploying your code, your existing application will fail until you deploy the new version. If you do it afterwards, there will be a period of time where it will fail because the indexes aren't correct.

If you just let Dynamoose update it for you, that isn't really recommended in production.

I feel like as part of this maybe something to consider would be a toggle to disable having strict conformance to indexes. Where the DynamoDB table can have more indexes than is defined in the schema, and Dynamoose won't complain.

What are the thoughts on that type of migration?

**Comment by dolsem** [comment]
@fishcharlie hmm imo directly disabling conformance to index would not be a good idea, because I think the schema should be the only source of truth for the data model used by the table. If we allow Dynamoose to do operations on a table that does not strictly conform to the present schema, this can lead to all sorts of bad issues.

However, what you describe is a nice use case for migrations. I wrote above, "This way if you forget to perform a migration the plugin will detect that your defined schema has a higher version that the one currently present in the table and throw an error." Instead of this there can be a toggle to revert to using older schema if migration has not been performed yet.

Consider the following update flow. You FIRST deploy your new backend version with the new schema. Dynamoose looks into migrations table and sees that your updated table is currently still using older schema version. It then uses that schema (since it's moved and stored in something like migrations/schemas) for all operations on the table. Then, once you run the migration it detects it from migrations table (perhaps with DynamoDB streams and if those are not enabled revert to polling) and switches to the new schema version. Once your migration is complete and your backend switches to the new schema version, you can safely delete older table if you want to.

The only question is, what should happen while migrations is in progress in a high-throughput application. If you continue updating old table you will lose it once you switch to the newer one. One way would be to just let DynamoDB return an error which should be caught by the backend which will then send something like "currently under maintenance" message. Or, to reduce the time backend goes offline, it can continue writing to the old table provided it has DynamoDB streams enabled, and after initial migration is complete it can process data in streams to bring new table up to date. It still means the backend will go offline for some short period of time, which is not great. I am not sure what a better solution might be.

**Comment by dolsem** [comment]
I think to solve this problem we can do dual-writing to both tables while migration is in progress. This time if an item gets updated during migration it gets put into both tables, and the code that walks the table and moves items over will only move an item if it does not yet exist in the new table.

**Comment by fishcharlie** [comment]
@dolsem I'm not sure I'm for having migrations create an entirely new table. I'd have to think about that a bit more. But at first thought, I'm not sure I'm for that. If you have a TON of documents and stuff stored in the database, that will be SUPER expensive and time consuming.

I personally can't think of any problems arising from having an index that exists on DynamoDB but not in the schema. That to me can't lead to any weird edge cases.

I'm for sure **not** a fan of Dynamoose throwing errors like `currently under maintenance` during migrations. Dynamoose should be as minimal as possible when it comes to this. I totally disagree with Dynamoose handling that much about your database. So I think we need to think of a better solution. Dynamoose should never throw errors unless it's an error from DynamoDB or an issue with the code you wrote interacting with Dynamoose.

I also get the feeling this should be created as a separate project (DynamooseCLI??) or integrated directly into Dynamoose. Maybe a plugin would make sense. But I'm not so sure about that.

---

One question I have, that I think is most important. What are some use cases and examples of things you think this should try to solve or tackle? Are we talking about renaming properties? Adding/removing indexes? Adding new properties? Changing the data for a given property (adding a prefix to every string value for a certain key)? Deleting properties?

Like what is the vision for this?

**Comment by dolsem** [comment]
Yes, it will indeed be very expensive and time consuming. However, migration by its nature is a very costly operation, because it affects all of your data. I think at the end of the day it's the developer's job to plan ahead and create versatile data models, so that migrations can be avoided as much as possible.

I also can't think of any safe solution that would not involve re-creating the table. In fact, since I created this thread I went and talked to a database expert (who specializes in SQL though), and in the SQL world, he told me, you usually take a snapshot of the table (like, import all data into CSV or something like that), then run scripts to convert it to the new data model, finally put it into a new table and run tests on it, making sure the data has been migrated correctly.

Of course, NoSQL is much more flexible in these things, but I still don't think it's a great idea to have different records in the same table follow different schemas, which is what will happen while we're performing an in-place migration. This also means that it's win or lose, if you screw up your code you might lose your data. If you create a new table though, you can always make sure you've migrated correctly before switching, and if you later find out something is not right, you can always switch back to the older one. Though I guess you might as well use database backups to solve this last problem.

I suppose letting Dynamoose work with the table if it has some indexes that are not defined in the schema is not a problem. I'm just not entirely sure why that would be useful. You mentioned creating indexes through AWS Console, well, personally I would just add that index to the schema and deploy new backend version. I think doing things like that declaratively makes more sense, because it makes it easy to retrace your steps if you need to. I would also prefer to have the complete data model in a single place, cause it also makes life easier. But if someone needs this feature, I really don't see a problem with it. BTW, I don't think it would be correct to call this a migration, because technically creating a new index does not move any of the data. Neither do things like adding a new field, nor, I believe, deleting a field, as long as you're fine losing the values stored inside.

I was under impression that by disabling conformance to indexes you implied ignoring a wider range of mismatches. For example, if there's an index defined on the table and the schema has an index with the same name but different structure, this can certainly create problems. I believe updating indexes almost always results in a migration, though we probably don't have to care about this one, because DynamoDB already handles it by itself. And note that unless I'm missing something, it would indeed just wipe the index table and re-create it from scratch, copying all the data over. Which is obviously very expensive.

I am myself completely opposed to any solution that would involve downtime and error messages during migration. I mentioned another solution in my second comment, so you can disregard the last paragraph of my previous comment, apologies for the flood. By double-writing to both tables during migration we can achieve two things: no downtime and an option to migrate data gradually over time. We can have it write to both tables which will naturally migrate data over time. In addition people will have an option to start a CLI process that will manually migrate the rest of the data if they don't want to wait. This will mitigate the problem of high cost when dealing with a lot of data.

As for Dynamoose CLI, personally I would not be committed to creating and maintaining such a project any time soon, I'm only interesting in CLI functionality that has to do with migrations. When Dynamoose CLI is a thing, it's possible to combine the two into one utility. I do agree that it probably doesn't make much sense to include that migration CLI tool directly into the main Dynamoose package. When I mentioned it I had a migration plugin in mind, which could have this CLI tool in its package. In fact, a migrations plugin probably makes most sense to me. I just haven't touched plugins before, and I don't yet know how much of Dynamoose is exposed to plugins and whether it's enough.

To give you an idea about real use cases I can give you one of mine. I have a React Native app with push notifications. Previously it was an Expo managed app and notifications were pushed through the Expo service, so there was a field in the Device table called "expoPushToken". Now that the app was ejected from Expo, I had to switch to Apple and Google push notification services with their own tokens. So I renamed "expoPushToken" to just "pushToken" and added a new enum field called pushNotificationService, which can be one of "apple", "google", or "expo". So all of the existing records should now have "pushNotificationService" field set to "expo" and value of "expoPushToken" moved to "pushToken". There was also an index dependent on these fields, so that should be re-created. So examples of common use cases would be renaming a field, adding a field and populating existing data with default value, changing hash key or range key of the table.
