### ISSUE TITLE
Unprocessed Items while batchWrite and batchGet

### ISSUE THREAD

**Issue by Nikhil2508** [dynamoosejs/dynamoose#658]
While doing a batchWrite some of the items were not written and I still got a success response. For example if I am writing 10 items I only got 7 in the table and 3 were missing. I believe that dynamodb does return a unprocessed items array in response but I cant find that in dynamoose. Is that available in dynamoose as well?

**Comment by fishcharlie** [comment]
Closing due to not filling out the issue template
