### ISSUE TITLE
how to update existing data with current value increment

### ISSUE THREAD

**Issue by derit** [dynamoosejs/dynamoose#676]
for example 

```
mynum = 1

mynum +=1  

mynum  values is 2
```

can i update value with += 1 in dynamoose

```
mydata.update({
id:1,
value: value + 1  << i need  like this  
})
```

**Comment by fishcharlie** [comment]
As mentioned in the issue template not filling out the complete issue template will cause your issue to be closed.

**Comment by rwilpert** [comment]
This would be very interesting for me as well. Is there actually a functionality like this?

DynamoDB support this as far as I am aware of by means of the UpdateExpressions. Should look something like this:
UpdateExpression='SET visits = visits + :inc'

Does dynamoose support this?
