### ISSUE TITLE
Travis ci build poblem on node 9

### ISSUE THREAD

**Issue by naciriii** [dynamoosejs/dynamoose#686]
@fishcharlie Travis's logs say 
```
npm ERR! code MODULE_NOT_FOUND

npm ERR! Cannot find module '../pack.js'
```
, while running `npm ci`. Pretty sure this is a CI issue, doesn't have anything to do with the PR itself.

_Originally posted by @dolsem in https://github.com/dynamoosejs/dynamoose/pull/645#issuecomment-520181749_
_Same here too
https://github.com/dynamoosejs/dynamoose/pull/685

**Comment by fishcharlie** [comment]
I talked to TravisCI about this. It looks to be some caching issue. If I delete the cache on Travis and rerun it, it works fine.

I think the end solution here is to move to GitHub Actions CI system once it's stable enough to meet our needs. Until then I'm just gonna have to handle the CI system more manually.
