### ISSUE TITLE
AWS Lambda - Don't include nested aws-sdk module

### ISSUE THREAD

**Issue by shivpatel** [dynamoosejs/dynamoose#705]
My Lambda zips have gotten considerably large since including this package. I see the entire aws-sdk is a dependency for this package. Is there anyway to get dynamoose to use the included aws-sdk provided when running in the Lambda env instead of install its own copy?

**Comment by fishcharlie** [comment]
Nope. This is part of NPM. The whole point is to ensure the dependencies exist, and there is no way currently for NPM to determine the AWS-SDK (and the correct version of the SDK) exists already.

Your best bet would be to build some system to manually copy the files over and install the dependencies manually. But I highly doubt that is worth the effort. It’d be easy to run into conflicts with versioning with the SDK and stuff and I can foresee a lot of random problems with that solution.

Another thing you could try would be forking the repo and removing AWS-SDK as a dependency. But you’d then have to manage merging in updates, and again, I’m not sure that is worth the effort for the minimal gains you’d get.
