### ISSUE TITLE
Use DynamoDB naming conventions

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#782]
This refers mostly to the documentation, but also to the code / function names:

I do suggest to stick to the naming conventions of DynamoDB as stated in the [AWS documentation](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithDynamo.html):

- document -> item
- hash key -> partition key
- range key -> sort key
- conditions -> There are key conditions (which selects items based on the primary key) and filters. Personally I would make that more clear in .query()

This is just what I found. Feel free to add more points to it.

In every case where this differs from MongoDB / Mongoose and also rational databases, I would write a note as dynamodbguide.com does this very good. Example for Document.md: `An item is a single data record in a table (similar to a row in a relational database or a document in MongoDB)`.

Also for partition key and range key I would add notes they are also known as hash key and range key.

As this introduces breaking changes for existing users, either this could be done in a major update (v1 -> v2 or v2 -> v3) and/or compatibility functions could be added to support the old syntax, too.

**Comment by fishcharlie** [comment]
There was a lot of discussion in Slack about this.

From my understanding the high level overview was:

1. `Document` is used in Mongoose, `Item` is used in DynamoDB
2. hash & range key is popular in the DynamoDB, even if not used in the DynamoDB documentation
    - Also hash & range key is used in the `aws-cli`, so even AWS is inconsistent here

One more note that wasn't discussed in Slack. But `Condition` is much more of a general concept. For example, you can pass a `Condition` instance into `Model.update` or other methods. It represents any condition.

---

Proposed next steps:

- Add aliases for `hashKey` to `partitionKey` & `rangeKey` to `sortKey`, while allowing existing versions to ensure backwards compatibility and not to majorly disrupt existing Dynamoose users experience with the library. It's extremely unlikely that we will ever remove the existing naming (even as a breaking change).
- Consider changing all instances from `Document` to `Item`
    - I'm more on board with this more recently. The further I dive into TypeScript, it looks like the name `Document` along with the name `Error` are gonna maybe cause problems. Since `Document`, is a concept in the DOM, and `Error` already exists. Maybe there is a way to fix it. But might just be easier to change it, especially since it's been brought up.

> As this introduces breaking changes for existing users, either this could be done in a major update (v1 -> v2 or v2 -> v3) and/or compatibility functions could be added to support the old syntax, too.

And with the proposed next steps above, no breaking changes will occur and can all happen in minor or patch versions.

**Comment by MickL** [comment]
I think the naming "partition key" is one of the most important things in DynamoDB modeling and an important difference to MongoDB: Items will be actually stored on different partitions, depending on the partition key, and then sorted by the sort key. Imo it is really important to know that this is not just a hash key, but the key for the partition that will result in performance and cost efficiency. The right partition key and sort key might be one of the key concepts (haha key!) of DynamoDB modeling so imo we should be on par with the documentation.

**Comment by fishcharlie** [comment]
I do think it's also extremely important to realize that the AWS-SDK uses the term `hash` and `range` key. This is truly an inconsistency on the part of AWS, which is slightly frustrating. Not sure if they have a reason for the inconsistency, but it's there.

The reality is when working in the code base the first goal is parity with Mongoose, sometimes that is not achievable given the structure of DynamoDB. The next best option is parity with AWS-SDK. Most of the time one of those two things is achievable. In fact I can't think of a situation where it's not. But as a last resort, we follow the documentation of DynamoDB, or come up with a custom solution.

For people working in code, hash and range key is used in AWS-SDK. So it's really **not** a Dynamoose problem, it's an AWS problem. Feel free to contact them and question their choices here.

---

All that being said, and after thinking about it more. I'm fine with documentation updates for this stuff. But it should only be referenced once. We don't need to say `partition key/hash key` every time we say `hash key`. Referencing it once is enough.

Not gonna accept any code level changes for this tho. Might reconsider in the future. But want more feedback from everyone else, and so far I haven't seen a lot of strong support from the larger community regarding this.

**Comment by fishcharlie** [comment]
A lot of documentation improvements have been made. Closing this for now. If anyone else has more opinions or thoughts feel free to comment and we can consider this further. I think it is much better now tho.
