### ISSUE TITLE
Create documentation website out of md files

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#784]
Possible solutions:

- mkdocs.org
- docsify.js.org
- gitbook.com

**Comment by fishcharlie** [comment]
I think this project used mkdocs.org before?? Need to check on that. For sure needs to be done before v2 is released.

**Comment by MickL** [comment]
Yes it did. If you do so, I would be willing improving the documentation to be more beginner friendly / readable.

**Comment by fishcharlie** [comment]
@MickL Do you have any suggestions/preference for which solution would be best here out of the ones you listed?

**Comment by fishcharlie** [comment]
Thinking about using the following technologies to make this happen:

- https://v2.docusaurus.io
- https://github.com/marketplace/actions/s3-sync

**Comment by fishcharlie** [comment]
Have a couple goals and objectives for how I wanna make the site a bit better and seems like those technologies has the best potential to make some of those goals happen.

**Comment by fishcharlie** [comment]
#828
