### ISSUE TITLE
Add typings for v2

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#785]
Currently there are not typings for use within TypeScript projects at all. 

The file should look like in v1, but be updated:
https://github.com/dynamoosejs/dynamoose/blob/v1.11.1/dynamoose.d.ts

**Comment by fishcharlie** [comment]
This is something I'm pretty opposed to in terms of a manually defined type file. As mentioned in the v2 rewrite ticket, TypeScript support originally was on the chopping block and not going to happen.

When hosting a manual type file in v1, there was a LOT of extra maintenance required. It was often forgotten about for months on end. That is not something I want to do or maintain again. Just not worth it.

I think my point is that if we are gonna support TypeScript, we are gonna support TypeScript. Dynamoose in the past has gone through phases where we half did it. I don't want to go through that again. I want to either commit to it, or not do it at all.

I'm at the point where we should just commit to it. There has been a lot of feedback about moving the project to TypeScript and it's a process that started in v1 as well. It didn't move fast enough and I wasn't knowledgeable enough at the time to continue it.

Checkout my proposal and initial thoughts here: #788. That will likely be updated as progress is made.
