### ISSUE TITLE
Add examples to documentation OR add an example project

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#786]
Either:

- The documentation could be extended by some actual code examples
- Create an example project showcasing most of the functionality

**Comment by fishcharlie** [comment]
@MickL Totally a fan of having example projects. Might wanna house them in a `dynamoosejs/examples` repo. I think it'd be great to have full complete working applications using Dynamoose. They can be simple like a Todo app or something. But stuff that can be practical and show how to use Dynamoose.

Any other ideas of what examples people would like to see?

**Comment by fishcharlie** [comment]
https://github.com/dynamoosejs/examples
