### ISSUE TITLE
Debug mode

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#794]
It would be awesome to have a debug mode that can be turned on and then logs the params out of a request made with aws-sdk. This could be useful for seeing if operations like query and indexes work as expected. 

Example output could be:

```
query:
{
  ExpressionAttributeValues: {
    ':s': {N: '2'},
    ':e' : {N: '09'},
    ':topic' : {S: 'PHRASE'}
  },
  KeyConditionExpression: 'Season = :s and Episode > :e',
  ProjectionExpression: 'Episode, Title, Subtitle',
  FilterExpression: 'contains (Subtitle, :topic)',
  TableName: 'EPISODES_TABLE'
}
```

**Comment by fishcharlie** [comment]
Closing since this is being tracked in #709

**Comment by ob-ivan** [comment]
I landed here after searching for a way to debug queries. @fishcharlie references #709, but that issue does not contain the word "debug", so the reference is unclear. It would be a nice addition to this thread if someone clarified how exactly #709 tracked the issue of a debug mode in dynamoose.
