### ISSUE TITLE
Projection on primary key

### ISSUE THREAD

**Issue by jerometea** [dynamoosejs/dynamoose#81]
Hello,

I have an user table and the primary key is the username. I want to query on the primary key and project only the firstname and the lastname. But when i do the query on the username Dynamoose retrieves all the attributes.

**The user schema :** 

var userSchema = new Schema({
	username : {
		type : String,
		hasKey : true,
		index: {
			global:true,
			name:'firstname-index',
			project:['firstname']
		}
	},
	provider :{
		type : String,
		required: true
	},
	firstname:{
		type:String,
	},
	lastname:{
		type:String
	},
	password:{
		type:String
	}
});

**The query :** 
User.query('username').eq('usernameTest').exec(function (err, userInfo) {
	  if(err) {
	  	console.log(err);
	  	console.log("error");
	  }
	  else {
	  	res.json(userInfo);
	  }
});

**Comment by brandongoode** [comment]
The reason you receiving all attributes is because 'username' is the hash key.  Dynamoose defaults to using the main table.  

Here's where the logic is default to the main table:
https://github.com/automategreen/dynamoose/blob/951cc453a04b7316dbd273aaccfaeac797d9b792/lib/Query.js#L80

**Comment by jerometea** [comment]
So is it possible to project just some attributes when I use the hash key ?

I may be wrong but "project" seems to not work.

In my DynamoDB Web Console I have this table : 

Primary Key                                   2 GSI
username      | email | provider | firstname | lastname | password

By using the AWS Console I created 2 GSI on the firstname attribute : 
- the 1st GSI projects all the attributes
- the 2nd GSI projects only the lastname and the email

In my user schema for the both GSI I set the projection like this : "project : ['lastname']"  and for the both GSI Dynamoose retrieves all the attributes ( for the 1st GSI ) or the email + email ( for the 2nd GSI ) but never only the lastname attribute.

Here is how I set the the firstname attribute in my schema : 
firstname:{
		type:String,
        index:{
            global:true,
            name:'firstname-index',
            project:['lastname']         
        }
	}`

**Comment by brandongoode** [comment]
Thanks for all the info. Sounds like a bug.  I'll run a few test myself.

**Comment by jerometea** [comment]
Can you keep me informed when it will ok, thank you!

**Comment by fishcharlie** [comment]
Dynamoose has gone through a lot of changes recently including the release of Dynamoose version 1.0.0. Due to that I'm closing this issue for now. Please test if this is still an issue on the latest version of Dynamoose, and you still run into problems please open a new issue and fill out all the fields in the issue template so we can properly debug, and mention this issue number in the new issue.

Thanks for using Dynamoose and we look forward to helping further if needed!
