### ISSUE TITLE
Creating a model with undefined attributes throws an error

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#815]
```
const User = new Schema({
   age: Number,
   id: {
       type: String,
       hashKey: true,
   },
   name: String,
})
```

```
User.create({
   age: undefined,
   id: 1,
   name: "Tim",
});
```

Note: The undefined attribute has to be the first attribute of the object.

Error: 
> Cannot convert undefined or null to object

Stacktrace: 
> at Function.keys (<anonymous>) at isValid (/Users/mick/git/myproject/node_modules/dynamoose/lib/Document.js:46:24)

**Comment by softmarshmallow** [comment]
Having the same problem. @MickL  Found a way out?
