### ISSUE TITLE
Option for a Schema to transform all attributes with empty strings to undefined

### ISSUE THREAD

**Issue by MickL** [dynamoosejs/dynamoose#820]
It would be awesome to have a config option for a Schema which, when set to true, ensures that all empty strings (which are not allowed by DynamoDB) are converted to undefined.

Additionally, there could be a second option to transform null to undefined.

Something like:

```
if (schemaConfig.removeEmptyString || schemaConfig.removeNull) {
      Object.keys(attributes).forEach(key => {
        if(schemaConfig.removeEmptyString && typeof attributes[key] === 'string' && attributes[key] === '') {
          delete attributes[key];
        }

        if(schemaConfig.removeNull && attributes[key] === null) {
          delete attributes[key];
        }
      })
    }
```

**Comment by fishcharlie** [comment]
This sounds like a much better plugin as opposed to part of the core library. I keep going back and forth between what should be part of the core library vs plugins. But this specifically is already possible using `set` settings for attributes. So I'm not sure how useful this will be.

I'm gonna close this for now to keep our issue tracker clean, since I don't foresee this being implemented anytime soon. If anyone else has more thoughts, please feel free to comment tho, and I'd be happy to hear more feedback about this.

**Comment by MickL** [comment]
How would I create and implement such a plugin? With the set function it has to be done for each and every attribute.

**Comment by fishcharlie** [comment]
> How would I create and implement such a plugin? With the set function it has to be done for each and every attribute.

@MickL Not possible as of right now. v1 had beta support for plugins but I didn’t like the architecture of it. For now you do have to set it on every attribute or build your own wrapper or something.

Would be open to considering get and set functions on the schema as well as the attributes tho. Which might help.

**Comment by fishcharlie** [comment]
It is now possible to save non-key empty string & binary attributes in DynamoDB. This functionality has been tested in the latest version of Dynamoose and works as expected.

https://twitter.com/dynamoosejs/status/1262482622191558656?s=21

**Comment by MickL** [comment]
Does this also effect saving `null`?

**Comment by fishcharlie** [comment]
@MickL Saving `null` has no updates at this point. https://dynamoosejs.com/other/FAQ#why-am-i-getting-strange-behavior-when-an-attribute-value-is-null-in-my-documents

It is on my radar, and hoping to work on it soon. Have a few other things that are higher priority tho.
